const BLOCKS_AUX_BY_LEMMA = {
  sein: {
    // Movimiento
    gehen: "sein",
    kommen: "sein",
    fahren: "sein",
    fliegen: "sein",
    laufen: "sein",
    schwimmen: "sein",
    springen: "sein",
    reisen: "sein",
    steigen: "sein",
    klettern: "sein",
    rennen: "sein",
    sinken: "sein",
    einsteigen: "sein",
    aussteigen: "sein",
    umsteigen: "sein",
    zurückkehren: "sein",
    eintreten: "sein",
    ankommen: "sein",
    ausgehen: "sein",
    zurückgehen: "sein",
    weggehen: "sein",

    // Cambio de estado
    werden: "sein",
    bleiben: "sein",
    sterben: "sein",
    einschlafen: "sein",
    aufwachen: "sein",
    wachsen: "sein",
    fallen: "sein",
    verschwinden: "sein",
    erscheinen: "sein",

    // Impersonales
    passieren: "sein",
    geschehen: "sein",
    gelingen: "sein",
    entstehen: "sein",
    misslingen: "sein",

    laufen: "sein",
    einsteigen: "sein",
    verschwinden: "sein",
    landen: "sein",
    abhauen: "sein",

    fallen: "sein",
  },

  haben: {
    // Transitivos básicos
    machen: "haben",
    essen: "haben",
    trinken: "haben",
    lesen: "haben",
    schreiben: "haben",
    kaufen: "haben",
    verkaufen: "haben",
    nehmen: "haben",
    bringen: "haben",
    holen: "haben",
    verlieren: "haben",
    finden: "haben",
    suchen: "haben",
    verstehen: "haben",
    erklären: "haben",
    lernen: "haben",
    studieren: "haben",
    benutzen: "haben",
    öffnen: "haben",
    schließen: "haben",
    anrufen: "haben",
    besuchen: "haben",
    sehen: "haben",
    hören: "haben",
    sagen: "haben",
    erzählen: "haben",
    fragen: "haben",
    antworten: "haben",
    kennen: "haben",
    wissen: "haben",
    denken: "haben",
    glauben: "haben",
    arbeiten: "haben",
    schlafen: "haben",
    warten: "haben",
    reden: "haben",
    wohnen: "haben",
    lachen: "haben",
    bezahlen: "haben",
    kosten: "haben",
    brauchen: "haben",
    bekommen: "haben",
    schicken: "haben",
    zeigen: "haben",
    feiern: "haben",
    spielen: "haben",
    telefonieren: "haben",
    leben: "haben",
    lieben: "haben",
    hoffen: "haben",
    gewinnen: "haben",
    abholen: "haben",
    abschließen: "haben",
    zusehen: "haben",
    helfen: "haben",

    basteln: "haben",
    drehen: "haben",
    wenden: "haben",
    gewinnen: "haben",
    nutzen: "haben",
    fassen: "haben",
    halten: "haben",
    versuchen: "haben",
    unterstützen: "haben",
    einhaken: "haben",
    weiterspinnen: "haben",
    weiterspinnen: "haben",
    entgegenlassen: "haben",
    behalten: "haben",
    hauen: "haben", // base; ver también "abhauen" arriba
    kriegen: "haben",
    bedeuten: "haben",
    aufziehen: "haben",
    stricken: "haben",
    treffen: "haben",
    suchen: "haben",
    finden: "haben",
    aufmachen: "haben",
    klauen: "haben",
    bringen: "haben", // ya estaba, pero no pasa nada si repites
    sagen: "haben",
    aufregen: "haben",
    schlagen: "haben",
    denken: "haben",
    greifen: "haben",
    vorliegen: "haben",
    hängen: "haben",
    treten: "haben", // ⚠️ ver nota: también puede usar "sein" intransitivo
    begehen: "haben",
    durchsägen: "haben",
    aufbereiten: "haben",
    erschaffen: "haben",

    tragen: "haben",
    lächeln: "haben",
    kämmen: "haben",
    richten: "haben",
    reichen: "haben",
    behandeln: "haben",
    frisieren: "haben",
    umschließen: "haben",
    befinden: "haben", // 'sich befinden' también usa 'haben'
    ziehen: "haben",

    herausstehen: "haben",
  },
};

export const AUX_BY_LEMMA = {
  ...BLOCKS_AUX_BY_LEMMA.sein,
  ...BLOCKS_AUX_BY_LEMMA.haben,
};
