export const IRREGULARS = {
  sein: {
    lemma: "sein",
    aux: "sein",
    praesens: {
      ich: "bin",
      du: "bist",
      "er/sie/es": "ist",
      wir: "sind",
      ihr: "seid",
      "sie/Sie": "sind",
    },
    präteritum: {
      ich: "war",
      du: "warst",
      "er/sie/es": "war",
      wir: "waren",
      ihr: "wart",
      "sie/Sie": "waren",
    },
    konjunktiv2: {
      ich: "wäre",
      du: "wärest",
      "er/sie/es": "wäre",
      wir: "wären",
      ihr: "wäret",
      "sie/Sie": "wären",
    },
    partizip2: "gewesen",
    imperativ: { du: "sei", ihr: "seid", Sie: "seien Sie" },
    zuInfinitiv: "zu sein",
  },

  haben: {
    lemma: "haben",
    aux: "haben",
    praesens: {
      ich: "habe",
      du: "hast",
      "er/sie/es": "hat",
      wir: "haben",
      ihr: "habt",
      "sie/Sie": "haben",
    },
    präteritum: {
      ich: "hatte",
      du: "hattest",
      "er/sie/es": "hatte",
      wir: "hatten",
      ihr: "hattet",
      "sie/Sie": "hatten",
    },
    konjunktiv2: {
      ich: "hätte",
      du: "hättest",
      "er/sie/es": "hätte",
      wir: "hätten",
      ihr: "hättet",
      "sie/Sie": "hätten",
    },
    partizip2: "gehabt",
    imperativ: { du: "hab", ihr: "habt", Sie: "haben Sie" },
    zuInfinitiv: "zu haben",
  },

  werden: {
    lemma: "werden",
    aux: "sein",
    praesens: {
      ich: "werde",
      du: "wirst",
      "er/sie/es": "wird",
      wir: "werden",
      ihr: "werdet",
      "sie/Sie": "werden",
    },
    präteritum: {
      ich: "wurde",
      du: "wurdest",
      "er/sie/es": "wurde",
      wir: "wurden",
      ihr: "wurdet",
      "sie/Sie": "wurden",
    },
    konjunktiv2: {
      ich: "würde",
      du: "würdest",
      "er/sie/es": "würde",
      wir: "würden",
      ihr: "würdet",
      "sie/Sie": "würden",
    },
    partizip2: "geworden",
    imperativ: { du: "werde", ihr: "werdet", Sie: "werden Sie" },
    zuInfinitiv: "zu werden",
  },

  gehen: {
    lemma: "gehen",
    aux: "sein",
    praesens: {
      ich: "gehe",
      du: "gehst",
      "er/sie/es": "geht",
      wir: "gehen",
      ihr: "geht",
      "sie/Sie": "gehen",
    },
    präteritum: {
      ich: "ging",
      du: "gingst",
      "er/sie/es": "ging",
      wir: "gingen",
      ihr: "gingt",
      "sie/Sie": "gingen",
    },
    partizip2: "gegangen",
    imperativ: { du: "geh", ihr: "geht", Sie: "gehen Sie" },
    zuInfinitiv: "zu gehen",
  },

  können: {
    lemma: "können",
    aux: "haben",
    praesens: {
      ich: "kann",
      du: "kannst",
      "er/sie/es": "kann",
      wir: "können",
      ihr: "könnt",
      "sie/Sie": "können",
    },
    präteritum: {
      ich: "konnte",
      du: "konntest",
      "er/sie/es": "konnte",
      wir: "konnten",
      ihr: "konntet",
      "sie/Sie": "konnten",
    },
    konjunktiv2: {
      ich: "könnte",
      du: "könntest",
      "er/sie/es": "könnte",
      wir: "könnten",
      ihr: "könntet",
      "sie/Sie": "könnten",
    },
    partizip2: "gekonnt",
    imperativ: {}, // modales no usan imperativo
    zuInfinitiv: "zu können",
  },

  müssen: {
    lemma: "müssen",
    aux: "haben",
    praesens: {
      ich: "muss",
      du: "musst",
      "er/sie/es": "muss",
      wir: "müssen",
      ihr: "müsst",
      "sie/Sie": "müssen",
    },
    präteritum: {
      ich: "musste",
      du: "musstest",
      "er/sie/es": "musste",
      wir: "mussten",
      ihr: "musstet",
      "sie/Sie": "mussten",
    },
    konjunktiv2: {
      ich: "müsste",
      du: "müsstest",
      "er/sie/es": "müsste",
      wir: "müssten",
      ihr: "müsstet",
      "sie/Sie": "müssten",
    },
    partizip2: "gemusst",
    imperativ: {},
    zuInfinitiv: "zu müssen",
  },

  wollen: {
    lemma: "wollen",
    aux: "haben",
    praesens: {
      ich: "will",
      du: "willst",
      "er/sie/es": "will",
      wir: "wollen",
      ihr: "wollt",
      "sie/Sie": "wollen",
    },
    präteritum: {
      ich: "wollte",
      du: "wolltest",
      "er/sie/es": "wollte",
      wir: "wollten",
      ihr: "wolltet",
      "sie/Sie": "wollten",
    },
    konjunktiv2: {
      ich: "wollte",
      du: "wolltest",
      "er/sie/es": "wollte",
      wir: "wollten",
      ihr: "wolltet",
      "sie/Sie": "wollten",
    },
    partizip2: "gewollt",
    imperativ: {},
    zuInfinitiv: "zu wollen",
  },

  sollen: {
    lemma: "sollen",
    aux: "haben",
    praesens: {
      ich: "soll",
      du: "sollst",
      "er/sie/es": "soll",
      wir: "sollen",
      ihr: "sollt",
      "sie/Sie": "sollen",
    },
    präteritum: {
      ich: "sollte",
      du: "solltest",
      "er/sie/es": "sollte",
      wir: "sollten",
      ihr: "solltet",
      "sie/Sie": "sollten",
    },
    konjunktiv2: {
      ich: "sollte",
      du: "solltest",
      "er/sie/es": "sollte",
      wir: "sollten",
      ihr: "solltet",
      "sie/Sie": "sollten",
    },
    partizip2: "gesollt",
    imperativ: {},
    zuInfinitiv: "zu sollen",
  },

  dürfen: {
    lemma: "dürfen",
    aux: "haben",
    praesens: {
      ich: "darf",
      du: "darfst",
      "er/sie/es": "darf",
      wir: "dürfen",
      ihr: "dürft",
      "sie/Sie": "dürfen",
    },
    präteritum: {
      ich: "durfte",
      du: "durftest",
      "er/sie/es": "durfte",
      wir: "durften",
      ihr: "durftet",
      "sie/Sie": "durften",
    },
    konjunktiv2: {
      ich: "dürfte",
      du: "dürftest",
      "er/sie/es": "dürfte",
      wir: "dürften",
      ihr: "dürftet",
      "sie/Sie": "dürften",
    },
    partizip2: "gedurft",
    imperativ: {},
    zuInfinitiv: "zu dürfen",
  },

  mögen: {
    lemma: "mögen",
    aux: "haben",
    praesens: {
      ich: "mag",
      du: "magst",
      "er/sie/es": "mag",
      wir: "mögen",
      ihr: "mögt",
      "sie/Sie": "mögen",
    },
    präteritum: {
      ich: "mochte",
      du: "mochtest",
      "er/sie/es": "mochte",
      wir: "mochten",
      ihr: "mochtet",
      "sie/Sie": "mochten",
    },
    konjunktiv2: {
      ich: "möchte",
      du: "möchtest",
      "er/sie/es": "möchte",
      wir: "möchten",
      ihr: "möchtet",
      "sie/Sie": "möchten",
    },
    partizip2: "gemocht",
    imperativ: {},
    zuInfinitiv: "zu mögen",
  },

  lassen: {
    lemma: "lassen",
    aux: "haben",
    praesens: {
      ich: "lasse",
      du: "lässt",
      "er/sie/es": "lässt",
      wir: "lassen",
      ihr: "lasst",
      "sie/Sie": "lassen",
    },
    präteritum: {
      ich: "ließ",
      du: "ließest",
      "er/sie/es": "ließ",
      wir: "ließen",
      ihr: "ließt",
      "sie/Sie": "ließen",
    },
    partizip2: "gelassen",
    imperativ: { du: "lass", ihr: "lasst", Sie: "lassen Sie" },
    zuInfinitiv: "zu lassen",
  },

  machen: {
    lemma: "machen",
    aux: "haben",
    praesens: {
      ich: "mache",
      du: "machst",
      "er/sie/es": "macht",
      wir: "machen",
      ihr: "macht",
      "sie/Sie": "machen",
    },
    präteritum: {
      ich: "machte",
      du: "machtest",
      "er/sie/es": "machte",
      wir: "machten",
      ihr: "machtet",
      "sie/Sie": "machten",
    },
    partizip2: "gemacht",
    imperativ: { du: "mach", ihr: "macht", Sie: "machen Sie" },
    zuInfinitiv: "zu machen",
  },

  kommen: {
    lemma: "kommen",
    aux: "sein",
    praesens: {
      ich: "komme",
      du: "kommst",
      "er/sie/es": "kommt",
      wir: "kommen",
      ihr: "kommt",
      "sie/Sie": "kommen",
    },
    präteritum: {
      ich: "kam",
      du: "kamst",
      "er/sie/es": "kam",
      wir: "kamen",
      ihr: "kamt",
      "sie/Sie": "kamen",
    },
    partizip2: "gekommen",
    imperativ: { du: "komm", ihr: "kommt", Sie: "kommen Sie" },
    zuInfinitiv: "zu kommen",
  },

  sehen: {
    lemma: "sehen",
    aux: "haben",
    praesens: {
      ich: "sehe",
      du: "siehst",
      "er/sie/es": "sieht",
      wir: "sehen",
      ihr: "seht",
      "sie/Sie": "sehen",
    },
    präteritum: {
      ich: "sah",
      du: "sahst",
      "er/sie/es": "sah",
      wir: "sahen",
      ihr: "saht",
      "sie/Sie": "sahen",
    },
    partizip2: "gesehen",
    imperativ: { du: "sieh", ihr: "seht", Sie: "sehen Sie" },
    zuInfinitiv: "zu sehen",
  },

  nehmen: {
    lemma: "nehmen",
    aux: "haben",
    praesens: {
      ich: "nehme",
      du: "nimmst",
      "er/sie/es": "nimmt",
      wir: "nehmen",
      ihr: "nehmt",
      "sie/Sie": "nehmen",
    },
    präteritum: {
      ich: "nahm",
      du: "nahmst",
      "er/sie/es": "nahm",
      wir: "nahmen",
      ihr: "nahmt",
      "sie/Sie": "nahmen",
    },
    partizip2: "genommen",
    imperativ: { du: "nimm", ihr: "nehmt", Sie: "nehmen Sie" },
    zuInfinitiv: "zu nehmen",
  },

  geben: {
    lemma: "geben",
    aux: "haben",
    praesens: {
      ich: "gebe",
      du: "gibst",
      "er/sie/es": "gibt",
      wir: "geben",
      ihr: "gebt",
      "sie/Sie": "geben",
    },
    präteritum: {
      ich: "gab",
      du: "gabst",
      "er/sie/es": "gab",
      wir: "gaben",
      ihr: "gabt",
      "sie/Sie": "gaben",
    },
    partizip2: "gegeben",
    imperativ: { du: "gib", ihr: "gebt", Sie: "geben Sie" },
    zuInfinitiv: "zu geben",
  },

  // Añadimos más verbos irregulares comunes
  fahren: {
    lemma: "fahren",
    aux: "sein", // cuando implica movimiento
    praesens: {
      ich: "fahre",
      du: "fährst",
      "er/sie/es": "fährt",
      wir: "fahren",
      ihr: "fahrt",
      "sie/Sie": "fahren",
    },
    präteritum: {
      ich: "fuhr",
      du: "fuhrst",
      "er/sie/es": "fuhr",
      wir: "fuhren",
      ihr: "fuhrt",
      "sie/Sie": "fuhren",
    },
    partizip2: "gefahren",
    imperativ: { du: "fahr", ihr: "fahrt", Sie: "fahren Sie" },
    zuInfinitiv: "zu fahren",
  },

  essen: {
    lemma: "essen",
    aux: "haben",
    praesens: {
      ich: "esse",
      du: "isst",
      "er/sie/es": "isst",
      wir: "essen",
      ihr: "esst",
      "sie/Sie": "essen",
    },
    präteritum: {
      ich: "aß",
      du: "aßest",
      "er/sie/es": "aß",
      wir: "aßen",
      ihr: "aßt",
      "sie/Sie": "aßen",
    },
    partizip2: "gegessen",
    imperativ: { du: "iss", ihr: "esst", Sie: "essen Sie" },
    zuInfinitiv: "zu essen",
  },

  trinken: {
    lemma: "trinken",
    aux: "haben",
    praesens: {
      ich: "trinke",
      du: "trinkst",
      "er/sie/es": "trinkt",
      wir: "trinken",
      ihr: "trinkt",
      "sie/Sie": "trinken",
    },
    präteritum: {
      ich: "trank",
      du: "trankst",
      "er/sie/es": "trank",
      wir: "tranken",
      ihr: "trankt",
      "sie/Sie": "tranken",
    },
    partizip2: "getrunken",
    imperativ: { du: "trink", ihr: "trinkt", Sie: "trinken Sie" },
    zuInfinitiv: "zu trinken",
  },

  stehen: {
    lemma: "stehen",
    aux: "haben",
    praesens: {
      ich: "stehe",
      du: "stehst",
      "er/sie/es": "steht",
      wir: "stehen",
      ihr: "steht",
      "sie/Sie": "stehen",
    },
    präteritum: {
      ich: "stand",
      du: "standest",
      "er/sie/es": "stand",
      wir: "standen",
      ihr: "standet",
      "sie/Sie": "standen",
    },
    partizip2: "gestanden",
    imperativ: { du: "steh", ihr: "steht", Sie: "stehen Sie" },
    zuInfinitiv: "zu stehen",
  },
  bleiben: {
    lemma: "bleiben",
    aux: "sein",
    praesens: {
      ich: "bleibe",
      du: "bleibst",
      "er/sie/es": "bleibt",
      wir: "bleiben",
      ihr: "bleibt",
      "sie/Sie": "bleiben",
    },
    präteritum: {
      ich: "blieb",
      du: "bliebst",
      "er/sie/es": "blieb",
      wir: "blieben",
      ihr: "bliebt",
      "sie/Sie": "blieben",
    },
    partizip2: "geblieben",
    imperativ: { du: "bleib", ihr: "bleibt", Sie: "bleiben Sie" },
    zuInfinitiv: "zu bleiben",
  },
  liegen: {
    lemma: "liegen",
    aux: "haben",
    praesens: {
      ich: "liege",
      du: "liegst",
      "er/sie/es": "liegt",
      wir: "liegen",
      ihr: "liegt",
      "sie/Sie": "liegen",
    },
    präteritum: {
      ich: "lag",
      du: "lagst",
      "er/sie/es": "lag",
      wir: "lagen",
      ihr: "lagt",
      "sie/Sie": "lagen",
    },
    partizip2: "gelegen",
    imperativ: { du: "lieg", ihr: "liegt", Sie: "liegen Sie" },
    zuInfinitiv: "zu liegen",
  },

  verstehen: {
    lemma: "verstehen",
    aux: "haben",
    praesens: {
      ich: "verstehe",
      du: "verstehst",
      "er/sie/es": "versteht",
      wir: "verstehen",
      ihr: "versteht",
      "sie/Sie": "verstehen",
    },
    präteritum: {
      ich: "verstand",
      du: "verstandest",
      "er/sie/es": "verstand",
      wir: "verstanden",
      ihr: "verstandet",
      "sie/Sie": "verstanden",
    },
    partizip2: "verstanden",
    imperativ: { du: "versteh", ihr: "versteht", Sie: "verstehen Sie" },
    zuInfinitiv: "zu verstehen",
  },
  zerlegen: {
    lemma: "zerlegen",
    aux: "haben",
    praesens: {
      ich: "zerlege",
      du: "zerlegst",
      "er/sie/es": "zerlegt",
      wir: "zerlegen",
      ihr: "zerlegt",
      "sie/Sie": "zerlegen",
    },
    präteritum: {
      ich: "zerlegte",
      du: "zerlegtest",
      "er/sie/es": "zerlegte",
      wir: "zerlegten",
      ihr: "zerlegtet",
      "sie/Sie": "zerlegten",
    },
    partizip2: "zerlegt",
    imperativ: { du: "zerleg", ihr: "zerlegt", Sie: "zerlegen Sie" },
    zuInfinitiv: "zu zerlegen",
  },

  aufnehmen: {
    lemma: "aufnehmen",
    aux: "haben",
    praesens: {
      ich: "nehme auf",
      du: "nimmst auf",
      "er/sie/es": "nimmt auf",
      wir: "nehmen auf",
      ihr: "nehmt auf",
      "sie/Sie": "nehmen auf",
    },
    präteritum: {
      ich: "nahm auf",
      du: "nahmst auf",
      "er/sie/es": "nahm auf",
      wir: "nahmen auf",
      ihr: "nahmt auf",
      "sie/Sie": "nahmen auf",
    },
    partizip2: "aufgenommen",
    imperativ: { du: "nimm auf", ihr: "nehmt auf", Sie: "nehmen Sie auf" },
    zuInfinitiv: "aufzunehmen",
  },

  schließen: {
    lemma: "schließen",
    aux: "haben",
    praesens: {
      ich: "schließe",
      du: "schließt",
      "er/sie/es": "schließt",
      wir: "schließen",
      ihr: "schließt",
      "sie/Sie": "schließen",
    },
    präteritum: {
      ich: "schloss",
      du: "schlossest",
      "er/sie/es": "schloss",
      wir: "schlossen",
      ihr: "schlosst",
      "sie/Sie": "schlossen",
    },
    partizip2: "geschlossen",
    imperativ: { du: "schließ", ihr: "schließt", Sie: "schließen Sie" },
    zuInfinitiv: "zu schließen",
  },

  abschließen: {
    lemma: "abschließen",
    aux: "haben",
    praesens: {
      ich: "schließe ab",
      du: "schließt ab",
      "er/sie/es": "schließt ab",
      wir: "schließen ab",
      ihr: "schließt ab",
      "sie/Sie": "schließen ab",
    },
    präteritum: {
      ich: "schloss ab",
      du: "schlossest ab",
      "er/sie/es": "schloss ab",
      wir: "schlossen ab",
      ihr: "schlosst ab",
      "sie/Sie": "schlossen ab",
    },
    partizip2: "abgeschlossen",
    imperativ: {
      du: "schließ ab",
      ihr: "schließt ab",
      Sie: "schließen Sie ab",
    },
    zuInfinitiv: "abzuschließen",
  },

  helfen: {
    lemma: "helfen",
    aux: "haben",
    praesens: {
      ich: "helfe",
      du: "hilfst",
      "er/sie/es": "hilft",
      wir: "helfen",
      ihr: "helft",
      "sie/Sie": "helfen",
    },
    präteritum: {
      ich: "half",
      du: "halfst",
      "er/sie/es": "half",
      wir: "halfen",
      ihr: "halft",
      "sie/Sie": "halfen",
    },
    partizip2: "geholfen",
    imperativ: { du: "hilf", ihr: "helft", Sie: "helfen Sie" },
    zuInfinitiv: "zu helfen",
  },

  schreiben: {
    lemma: "schreiben",
    aux: "haben",
    praesens: {
      ich: "schreibe",
      du: "schreibst",
      "er/sie/es": "schreibt",
      wir: "schreiben",
      ihr: "schriebt",
      "sie/Sie": "schreiben",
    },
    präteritum: {
      ich: "schrieb",
      du: "schriebst",
      "er/sie/es": "schrieb",
      wir: "schrieben",
      ihr: "schriebt",
      "sie/Sie": "schrieben",
    },
    partizip2: "geschrieben",
    imperativ: { du: "schreib", ihr: "schreibt", Sie: "schreiben Sie" },
    zuInfinitiv: "zu schreiben",
  },

  lesen: {
    lemma: "lesen",
    aux: "haben",
    praesens: {
      ich: "lese",
      du: "liest",
      "er/sie/es": "liest",
      wir: "lesen",
      ihr: "lest",
      "sie/Sie": "lesen",
    },
    präteritum: {
      ich: "las",
      du: "lasest",
      "er/sie/es": "las",
      wir: "lasen",
      ihr: "last",
      "sie/Sie": "lasen",
    },
    partizip2: "gelesen",
    imperativ: { du: "lies", ihr: "lest", Sie: "lesen Sie" },
    zuInfinitiv: "zu lesen",
  },

  wissen: {
    lemma: "wissen",
    aux: "haben",
    praesens: {
      ich: "weiß",
      du: "weißt",
      "er/sie/es": "weiß",
      wir: "wissen",
      ihr: "wisst",
      "sie/Sie": "wissen",
    },
    präteritum: {
      ich: "wusste",
      du: "wusstest",
      "er/sie/es": "wusste",
      wir: "wussten",
      ihr: "wusstet",
      "sie/Sie": "wussten",
    },
    partizip2: "gewusst",
    imperativ: { du: "wisse", ihr: "wisst", Sie: "wissen Sie" },
    zuInfinitiv: "zu wissen",
  },

  bemerken: {
    lemma: "bemerken",
    aux: "haben",
    praesens: {
      ich: "bemerke",
      du: "bemerkst",
      "er/sie/es": "bemerkt",
      wir: "bemerken",
      ihr: "bemerkt",
      "sie/Sie": "bemerken",
    },
    präteritum: {
      ich: "bemerkte",
      du: "bemerktest",
      "er/sie/es": "bemerkte",
      wir: "bemerkten",
      ihr: "bemerktet",
      "sie/Sie": "bemerkten",
    },
    partizip2: "bemerkt",
    imperativ: { du: "bemerk", ihr: "bemerkt", Sie: "bemerken Sie" },
    zuInfinitiv: "zu bemerken",
  },

  wirken: {
    lemma: "wirken",
    aux: "haben",
    praesens: {
      ich: "wirke",
      du: "wirkst",
      "er/sie/es": "wirkt",
      wir: "wirken",
      ihr: "wirkt",
      "sie/Sie": "wirken",
    },
    präteritum: {
      ich: "wirkte",
      du: "wirktest",
      "er/sie/es": "wirkte",
      wir: "wirkten",
      ihr: "wirktet",
      "sie/Sie": "wirkten",
    },
    partizip2: "gewirkt",
    imperativ: { du: "wirk", ihr: "wirkt", Sie: "wirken Sie" },
    zuInfinitiv: "zu wirken",
  },

  scheinen: {
    lemma: "scheinen",
    aux: "haben",
    praesens: {
      ich: "scheine",
      du: "scheinst",
      "er/sie/es": "scheint",
      wir: "scheinen",
      ihr: "scheint",
      "sie/Sie": "scheinen",
    },
    präteritum: {
      ich: "schien",
      du: "schienst",
      "er/sie/es": "schien",
      wir: "schienen",
      ihr: "schient",
      "sie/Sie": "schienen",
    },
    partizip2: "geschienen",
    imperativ: { du: "schein", ihr: "scheint", Sie: "scheinen Sie" },
    zuInfinitiv: "zu scheinen",
  },

  erkennen: {
    lemma: "erkennen",
    aux: "haben",
    praesens: {
      ich: "erkenne",
      du: "erkennst",
      "er/sie/es": "erkennt",
      wir: "erkennen",
      ihr: "erkennt",
      "sie/Sie": "erkennen",
    },
    präteritum: {
      ich: "erkannte",
      du: "erkanntest",
      "er/sie/es": "erkannte",
      wir: "erkannten",
      ihr: "erkanntet",
      "sie/Sie": "erkannten",
    },
    partizip2: "erkannt",
    imperativ: { du: "erkenn", ihr: "erkennt", Sie: "erkennen Sie" },
    zuInfinitiv: "zu erkennen",
  },

  erstrecken: {
    lemma: "erstrecken",
    aux: "haben",
    praesens: {
      ich: "erstrecke",
      du: "erstreckst",
      "er/sie/es": "erstreckt",
      wir: "erstrecken",
      ihr: "erstreckt",
      "sie/Sie": "erstrecken",
    },
    präteritum: {
      ich: "erstreckte",
      du: "erstrecktest",
      "er/sie/es": "erstreckte",
      wir: "erstreckten",
      ihr: "erstrecktet",
      "sie/Sie": "erstreckten",
    },
    partizip2: "erstreckt",
    imperativ: { du: "erstreck", ihr: "erstreckt", Sie: "erstrecken Sie" },
    zuInfinitiv: "zu erstrecken",
  },
};
