export const IRREGULARS = {
  sein: {
    lemma: "sein",
    aux: "sein",
    praesens: {
      ich: "bin",
      du: "bist",
      "er/sie/es": "ist",
      wir: "sind",
      ihr: "seid",
      "sie/Sie": "sind",
    },
    präteritum: {
      ich: "war",
      du: "warst",
      "er/sie/es": "war",
      wir: "waren",
      ihr: "wart",
      "sie/Sie": "waren",
    },
    konjunktiv2: {
      ich: "wäre",
      du: ["wärest", "wärst"],
      "er/sie/es": "wäre",
      wir: "wären",
      ihr: ["wäret", "wärt"],
      "sie/Sie": "wären",
    },
    partizip2: "gewesen",
    imperativ: { du: "sei", ihr: "seid", Sie: "seien Sie" },
    zuInfinitiv: "zu sein",
  },

  haben: {
    lemma: "haben",
    aux: "haben",
    praesens: {
      ich: "habe",
      du: "hast",
      "er/sie/es": "hat",
      wir: "haben",
      ihr: "habt",
      "sie/Sie": "haben",
    },
    präteritum: {
      ich: "hatte",
      du: "hattest",
      "er/sie/es": "hatte",
      wir: "hatten",
      ihr: "hattet",
      "sie/Sie": "hatten",
    },
    konjunktiv2: {
      ich: "hätte",
      du: "hättest",
      "er/sie/es": "hätte",
      wir: "hätten",
      ihr: "hättet",
      "sie/Sie": "hätten",
    },
    partizip2: "gehabt",
    imperativ: { du: "hab", ihr: "habt", Sie: "haben Sie" },
    zuInfinitiv: "zu haben",
  },

  werden: {
    lemma: "werden",
    aux: "sein",
    praesens: {
      ich: "werde",
      du: "wirst",
      "er/sie/es": "wird",
      wir: "werden",
      ihr: "werdet",
      "sie/Sie": "werden",
    },
    präteritum: {
      ich: "wurde",
      du: "wurdest",
      "er/sie/es": "wurde",
      wir: "wurden",
      ihr: "wurdet",
      "sie/Sie": "wurden",
    },
    konjunktiv2: {
      ich: "würde",
      du: "würdest",
      "er/sie/es": "würde",
      wir: "würden",
      ihr: "würdet",
      "sie/Sie": "würden",
    },
    partizip2: {
      aktiv: "geworden",
      passiv: "worden",
    },
    imperativ: { du: "werde", ihr: "werdet", Sie: "werden Sie" },
    zuInfinitiv: "zu werden",
  },

  gehen: {
    lemma: "gehen",
    aux: "sein",
    praesens: {
      ich: "gehe",
      du: "gehst",
      "er/sie/es": "geht",
      wir: "gehen",
      ihr: "geht",
      "sie/Sie": "gehen",
    },
    präteritum: {
      ich: "ging",
      du: "gingst",
      "er/sie/es": "ging",
      wir: "gingen",
      ihr: "gingt",
      "sie/Sie": "gingen",
    },
    partizip2: "gegangen",
    imperativ: { du: "geh", ihr: "geht", Sie: "gehen Sie" },
    zuInfinitiv: "zu gehen",
  },

  können: {
    lemma: "können",
    aux: "haben",
    praesens: {
      ich: "kann",
      du: "kannst",
      "er/sie/es": "kann",
      wir: "können",
      ihr: "könnt",
      "sie/Sie": "können",
    },
    präteritum: {
      ich: "konnte",
      du: "konntest",
      "er/sie/es": "konnte",
      wir: "konnten",
      ihr: "konntet",
      "sie/Sie": "konnten",
    },
    konjunktiv2: {
      ich: "könnte",
      du: "könntest",
      "er/sie/es": "könnte",
      wir: "könnten",
      ihr: "könntet",
      "sie/Sie": "könnten",
    },
    partizip2: "gekonnt",
    imperativ: {}, // modales no usan imperativo
    zuInfinitiv: "zu können",
  },

  müssen: {
    lemma: "müssen",
    aux: "haben",
    praesens: {
      ich: "muss",
      du: "musst",
      "er/sie/es": "muss",
      wir: "müssen",
      ihr: "müsst",
      "sie/Sie": "müssen",
    },
    präteritum: {
      ich: "musste",
      du: "musstest",
      "er/sie/es": "musste",
      wir: "mussten",
      ihr: "musstet",
      "sie/Sie": "mussten",
    },
    konjunktiv2: {
      ich: "müsste",
      du: "müsstest",
      "er/sie/es": "müsste",
      wir: "müssten",
      ihr: "müsstet",
      "sie/Sie": "müssten",
    },
    partizip2: "gemusst",
    imperativ: {},
    zuInfinitiv: "zu müssen",
  },

  wollen: {
    lemma: "wollen",
    aux: "haben",
    praesens: {
      ich: "will",
      du: "willst",
      "er/sie/es": "will",
      wir: "wollen",
      ihr: "wollt",
      "sie/Sie": "wollen",
    },
    präteritum: {
      ich: "wollte",
      du: "wolltest",
      "er/sie/es": "wollte",
      wir: "wollten",
      ihr: "wolltet",
      "sie/Sie": "wollten",
    },
    konjunktiv2: {
      ich: "wollte",
      du: "wolltest",
      "er/sie/es": "wollte",
      wir: "wollten",
      ihr: "wolltet",
      "sie/Sie": "wollten",
    },
    partizip2: "gewollt",
    imperativ: {},
    zuInfinitiv: "zu wollen",
  },

  sollen: {
    lemma: "sollen",
    aux: "haben",
    praesens: {
      ich: "soll",
      du: "sollst",
      "er/sie/es": "soll",
      wir: "sollen",
      ihr: "sollt",
      "sie/Sie": "sollen",
    },
    präteritum: {
      ich: "sollte",
      du: "solltest",
      "er/sie/es": "sollte",
      wir: "sollten",
      ihr: "solltet",
      "sie/Sie": "sollten",
    },
    konjunktiv2: {
      ich: "sollte",
      du: "solltest",
      "er/sie/es": "sollte",
      wir: "sollten",
      ihr: "solltet",
      "sie/Sie": "sollten",
    },
    partizip2: "gesollt",
    imperativ: {},
    zuInfinitiv: "zu sollen",
  },

  dürfen: {
    lemma: "dürfen",
    aux: "haben",
    praesens: {
      ich: "darf",
      du: "darfst",
      "er/sie/es": "darf",
      wir: "dürfen",
      ihr: "dürft",
      "sie/Sie": "dürfen",
    },
    präteritum: {
      ich: "durfte",
      du: "durftest",
      "er/sie/es": "durfte",
      wir: "durften",
      ihr: "durftet",
      "sie/Sie": "durften",
    },
    konjunktiv2: {
      ich: "dürfte",
      du: "dürftest",
      "er/sie/es": "dürfte",
      wir: "dürften",
      ihr: "dürftet",
      "sie/Sie": "dürften",
    },
    partizip2: "gedurft",
    imperativ: {},
    zuInfinitiv: "zu dürfen",
  },

  mögen: {
    lemma: "mögen",
    aux: "haben",
    praesens: {
      ich: "mag",
      du: "magst",
      "er/sie/es": "mag",
      wir: "mögen",
      ihr: "mögt",
      "sie/Sie": "mögen",
    },
    präteritum: {
      ich: "mochte",
      du: "mochtest",
      "er/sie/es": "mochte",
      wir: "mochten",
      ihr: "mochtet",
      "sie/Sie": "mochten",
    },
    konjunktiv2: {
      ich: "möchte",
      du: "möchtest",
      "er/sie/es": "möchte",
      wir: "möchten",
      ihr: "möchtet",
      "sie/Sie": "möchten",
    },
    partizip2: "gemocht",
    imperativ: {},
    zuInfinitiv: "zu mögen",
  },

  lassen: {
    lemma: "lassen",
    aux: "haben",
    praesens: {
      ich: "lasse",
      du: "lässt",
      "er/sie/es": "lässt",
      wir: "lassen",
      ihr: "lasst",
      "sie/Sie": "lassen",
    },
    präteritum: {
      ich: "ließ",
      du: "ließest",
      "er/sie/es": "ließ",
      wir: "ließen",
      ihr: "ließt",
      "sie/Sie": "ließen",
    },
    partizip2: "gelassen",
    imperativ: { du: "lass", ihr: "lasst", Sie: "lassen Sie" },
    zuInfinitiv: "zu lassen",
  },

  machen: {
    lemma: "machen",
    aux: "haben",
    praesens: {
      ich: "mache",
      du: "machst",
      "er/sie/es": "macht",
      wir: "machen",
      ihr: "macht",
      "sie/Sie": "machen",
    },
    präteritum: {
      ich: "machte",
      du: "machtest",
      "er/sie/es": "machte",
      wir: "machten",
      ihr: "machtet",
      "sie/Sie": "machten",
    },
    partizip2: "gemacht",
    imperativ: { du: "mach", ihr: "macht", Sie: "machen Sie" },
    zuInfinitiv: "zu machen",
  },

  kommen: {
    lemma: "kommen",
    aux: "sein",
    praesens: {
      ich: "komme",
      du: "kommst",
      "er/sie/es": "kommt",
      wir: "kommen",
      ihr: "kommt",
      "sie/Sie": "kommen",
    },
    präteritum: {
      ich: "kam",
      du: "kamst",
      "er/sie/es": "kam",
      wir: "kamen",
      ihr: "kamt",
      "sie/Sie": "kamen",
    },
    partizip2: "gekommen",
    imperativ: { du: "komm", ihr: "kommt", Sie: "kommen Sie" },
    zuInfinitiv: "zu kommen",
  },

  sehen: {
    lemma: "sehen",
    aux: "haben",
    praesens: {
      ich: "sehe",
      du: "siehst",
      "er/sie/es": "sieht",
      wir: "sehen",
      ihr: "seht",
      "sie/Sie": "sehen",
    },
    präteritum: {
      ich: "sah",
      du: "sahst",
      "er/sie/es": "sah",
      wir: "sahen",
      ihr: "saht",
      "sie/Sie": "sahen",
    },
    partizip2: "gesehen",
    imperativ: { du: "sieh", ihr: "seht", Sie: "sehen Sie" },
    zuInfinitiv: "zu sehen",
  },

  nehmen: {
    lemma: "nehmen",
    aux: "haben",
    praesens: {
      ich: "nehme",
      du: "nimmst",
      "er/sie/es": "nimmt",
      wir: "nehmen",
      ihr: "nehmt",
      "sie/Sie": "nehmen",
    },
    präteritum: {
      ich: "nahm",
      du: "nahmst",
      "er/sie/es": "nahm",
      wir: "nahmen",
      ihr: "nahmt",
      "sie/Sie": "nahmen",
    },
    partizip2: "genommen",
    imperativ: { du: "nimm", ihr: "nehmt", Sie: "nehmen Sie" },
    zuInfinitiv: "zu nehmen",
  },

  geben: {
    lemma: "geben",
    aux: "haben",
    praesens: {
      ich: "gebe",
      du: "gibst",
      "er/sie/es": "gibt",
      wir: "geben",
      ihr: "gebt",
      "sie/Sie": "geben",
    },
    präteritum: {
      ich: "gab",
      du: "gabst",
      "er/sie/es": "gab",
      wir: "gaben",
      ihr: "gabt",
      "sie/Sie": "gaben",
    },
    partizip2: "gegeben",
    imperativ: { du: "gib", ihr: "gebt", Sie: "geben Sie" },
    zuInfinitiv: "zu geben",
  },

  fahren: {
    lemma: "fahren",
    aux: "sein", // cuando implica movimiento
    praesens: {
      ich: "fahre",
      du: "fährst",
      "er/sie/es": "fährt",
      wir: "fahren",
      ihr: "fahrt",
      "sie/Sie": "fahren",
    },
    präteritum: {
      ich: "fuhr",
      du: "fuhrst",
      "er/sie/es": "fuhr",
      wir: "fuhren",
      ihr: "fuhrt",
      "sie/Sie": "fuhren",
    },
    partizip2: "gefahren",
    imperativ: { du: "fahr", ihr: "fahrt", Sie: "fahren Sie" },
    zuInfinitiv: "zu fahren",
  },

  essen: {
    lemma: "essen",
    aux: "haben",
    praesens: {
      ich: "esse",
      du: "isst",
      "er/sie/es": "isst",
      wir: "essen",
      ihr: "esst",
      "sie/Sie": "essen",
    },
    präteritum: {
      ich: "aß",
      du: "aßest",
      "er/sie/es": "aß",
      wir: "aßen",
      ihr: "aßt",
      "sie/Sie": "aßen",
    },
    partizip2: "gegessen",
    imperativ: { du: "iss", ihr: "esst", Sie: "essen Sie" },
    zuInfinitiv: "zu essen",
  },

  trinken: {
    lemma: "trinken",
    aux: "haben",
    praesens: {
      ich: "trinke",
      du: "trinkst",
      "er/sie/es": "trinkt",
      wir: "trinken",
      ihr: "trinkt",
      "sie/Sie": "trinken",
    },
    präteritum: {
      ich: "trank",
      du: "trankst",
      "er/sie/es": "trank",
      wir: "tranken",
      ihr: "trankt",
      "sie/Sie": "tranken",
    },
    partizip2: "getrunken",
    imperativ: { du: "trink", ihr: "trinkt", Sie: "trinken Sie" },
    zuInfinitiv: "zu trinken",
  },

  stehen: {
    lemma: "stehen",
    aux: "haben",
    praesens: {
      ich: "stehe",
      du: "stehst",
      "er/sie/es": "steht",
      wir: "stehen",
      ihr: "steht",
      "sie/Sie": "stehen",
    },
    präteritum: {
      ich: "stand",
      du: "standest",
      "er/sie/es": "stand",
      wir: "standen",
      ihr: "standet",
      "sie/Sie": "standen",
    },
    partizip2: "gestanden",
    imperativ: { du: "steh", ihr: "steht", Sie: "stehen Sie" },
    zuInfinitiv: "zu stehen",
  },
  bleiben: {
    lemma: "bleiben",
    aux: "sein",
    praesens: {
      ich: "bleibe",
      du: "bleibst",
      "er/sie/es": "bleibt",
      wir: "bleiben",
      ihr: "bleibt",
      "sie/Sie": "bleiben",
    },
    präteritum: {
      ich: "blieb",
      du: "bliebst",
      "er/sie/es": "blieb",
      wir: "blieben",
      ihr: "bliebt",
      "sie/Sie": "blieben",
    },
    partizip2: "geblieben",
    imperativ: { du: "bleib", ihr: "bleibt", Sie: "bleiben Sie" },
    zuInfinitiv: "zu bleiben",
  },
  liegen: {
    lemma: "liegen",
    aux: "haben",
    praesens: {
      ich: "liege",
      du: "liegst",
      "er/sie/es": "liegt",
      wir: "liegen",
      ihr: "liegt",
      "sie/Sie": "liegen",
    },
    präteritum: {
      ich: "lag",
      du: "lagst",
      "er/sie/es": "lag",
      wir: "lagen",
      ihr: "lagt",
      "sie/Sie": "lagen",
    },
    partizip2: "gelegen",
    imperativ: { du: "lieg", ihr: "liegt", Sie: "liegen Sie" },
    zuInfinitiv: "zu liegen",
  },

  verstehen: {
    lemma: "verstehen",
    aux: "haben",
    praesens: {
      ich: "verstehe",
      du: "verstehst",
      "er/sie/es": "versteht",
      wir: "verstehen",
      ihr: "versteht",
      "sie/Sie": "verstehen",
    },
    präteritum: {
      ich: "verstand",
      du: "verstandest",
      "er/sie/es": "verstand",
      wir: "verstanden",
      ihr: "verstandet",
      "sie/Sie": "verstanden",
    },
    partizip2: "verstanden",
    imperativ: { du: "versteh", ihr: "versteht", Sie: "verstehen Sie" },
    zuInfinitiv: "zu verstehen",
  },
  zerlegen: {
    lemma: "zerlegen",
    aux: "haben",
    praesens: {
      ich: "zerlege",
      du: "zerlegst",
      "er/sie/es": "zerlegt",
      wir: "zerlegen",
      ihr: "zerlegt",
      "sie/Sie": "zerlegen",
    },
    präteritum: {
      ich: "zerlegte",
      du: "zerlegtest",
      "er/sie/es": "zerlegte",
      wir: "zerlegten",
      ihr: "zerlegtet",
      "sie/Sie": "zerlegten",
    },
    partizip2: "zerlegt",
    imperativ: { du: "zerleg", ihr: "zerlegt", Sie: "zerlegen Sie" },
    zuInfinitiv: "zu zerlegen",
  },

  aufnehmen: {
    lemma: "aufnehmen",
    aux: "haben",
    praesens: {
      ich: "nehme auf",
      du: "nimmst auf",
      "er/sie/es": "nimmt auf",
      wir: "nehmen auf",
      ihr: "nehmt auf",
      "sie/Sie": "nehmen auf",
    },
    präteritum: {
      ich: "nahm auf",
      du: "nahmst auf",
      "er/sie/es": "nahm auf",
      wir: "nahmen auf",
      ihr: "nahmt auf",
      "sie/Sie": "nahmen auf",
    },
    partizip2: "aufgenommen",
    imperativ: { du: "nimm auf", ihr: "nehmt auf", Sie: "nehmen Sie auf" },
    zuInfinitiv: "aufzunehmen",
  },

  schließen: {
    lemma: "schließen",
    aux: "haben",
    praesens: {
      ich: "schließe",
      du: "schließt",
      "er/sie/es": "schließt",
      wir: "schließen",
      ihr: "schließt",
      "sie/Sie": "schließen",
    },
    präteritum: {
      ich: "schloss",
      du: "schlossest",
      "er/sie/es": "schloss",
      wir: "schlossen",
      ihr: "schlosst",
      "sie/Sie": "schlossen",
    },
    partizip2: "geschlossen",
    imperativ: { du: "schließ", ihr: "schließt", Sie: "schließen Sie" },
    zuInfinitiv: "zu schließen",
  },

  abschließen: {
    lemma: "abschließen",
    aux: "haben",
    praesens: {
      ich: "schließe ab",
      du: "schließt ab",
      "er/sie/es": "schließt ab",
      wir: "schließen ab",
      ihr: "schließt ab",
      "sie/Sie": "schließen ab",
    },
    präteritum: {
      ich: "schloss ab",
      du: "schlossest ab",
      "er/sie/es": "schloss ab",
      wir: "schlossen ab",
      ihr: "schlosst ab",
      "sie/Sie": "schlossen ab",
    },
    partizip2: "abgeschlossen",
    imperativ: {
      du: "schließ ab",
      ihr: "schließt ab",
      Sie: "schließen Sie ab",
    },
    zuInfinitiv: "abzuschließen",
  },

  helfen: {
    lemma: "helfen",
    aux: "haben",
    praesens: {
      ich: "helfe",
      du: "hilfst",
      "er/sie/es": "hilft",
      wir: "helfen",
      ihr: "helft",
      "sie/Sie": "helfen",
    },
    präteritum: {
      ich: "half",
      du: "halfst",
      "er/sie/es": "half",
      wir: "halfen",
      ihr: "halft",
      "sie/Sie": "halfen",
    },
    partizip2: "geholfen",
    imperativ: { du: "hilf", ihr: "helft", Sie: "helfen Sie" },
    zuInfinitiv: "zu helfen",
  },

  schreiben: {
    lemma: "schreiben",
    aux: "haben",
    praesens: {
      ich: "schreibe",
      du: "schreibst",
      "er/sie/es": "schreibt",
      wir: "schreiben",
      ihr: "schreibt",
      "sie/Sie": "schreiben",
    },
    präteritum: {
      ich: "schrieb",
      du: "schriebst",
      "er/sie/es": "schrieb",
      wir: "schrieben",
      ihr: "schriebt",
      "sie/Sie": "schrieben",
    },
    partizip2: "geschrieben",
    imperativ: { du: "schreib", ihr: "schreibt", Sie: "schreiben Sie" },
    zuInfinitiv: "zu schreiben",
  },

  lesen: {
    lemma: "lesen",
    aux: "haben",
    praesens: {
      ich: "lese",
      du: "liest",
      "er/sie/es": "liest",
      wir: "lesen",
      ihr: "lest",
      "sie/Sie": "lesen",
    },
    präteritum: {
      ich: "las",
      du: "lasest",
      "er/sie/es": "las",
      wir: "lasen",
      ihr: "last",
      "sie/Sie": "lasen",
    },
    partizip2: "gelesen",
    imperativ: { du: "lies", ihr: "lest", Sie: "lesen Sie" },
    zuInfinitiv: "zu lesen",
  },

  wissen: {
    lemma: "wissen",
    aux: "haben",
    praesens: {
      ich: "weiß",
      du: "weißt",
      "er/sie/es": "weiß",
      wir: "wissen",
      ihr: "wisst",
      "sie/Sie": "wissen",
    },
    präteritum: {
      ich: "wusste",
      du: "wusstest",
      "er/sie/es": "wusste",
      wir: "wussten",
      ihr: "wusstet",
      "sie/Sie": "wussten",
    },
    partizip2: "gewusst",
    imperativ: { du: "wisse", ihr: "wisst", Sie: "wissen Sie" },
    zuInfinitiv: "zu wissen",
  },

  bemerken: {
    lemma: "bemerken",
    aux: "haben",
    praesens: {
      ich: "bemerke",
      du: "bemerkst",
      "er/sie/es": "bemerkt",
      wir: "bemerken",
      ihr: "bemerkt",
      "sie/Sie": "bemerken",
    },
    präteritum: {
      ich: "bemerkte",
      du: "bemerktest",
      "er/sie/es": "bemerkte",
      wir: "bemerkten",
      ihr: "bemerktet",
      "sie/Sie": "bemerkten",
    },
    partizip2: "bemerkt",
    imperativ: { du: "bemerk", ihr: "bemerkt", Sie: "bemerken Sie" },
    zuInfinitiv: "zu bemerken",
  },

  wirken: {
    lemma: "wirken",
    aux: "haben",
    praesens: {
      ich: "wirke",
      du: "wirkst",
      "er/sie/es": "wirkt",
      wir: "wirken",
      ihr: "wirkt",
      "sie/Sie": "wirken",
    },
    präteritum: {
      ich: "wirkte",
      du: "wirktest",
      "er/sie/es": "wirkte",
      wir: "wirkten",
      ihr: "wirktet",
      "sie/Sie": "wirkten",
    },
    partizip2: "gewirkt",
    imperativ: { du: "wirk", ihr: "wirkt", Sie: "wirken Sie" },
    zuInfinitiv: "zu wirken",
  },

  scheinen: {
    lemma: "scheinen",
    aux: "haben",
    praesens: {
      ich: "scheine",
      du: "scheinst",
      "er/sie/es": "scheint",
      wir: "scheinen",
      ihr: "scheint",
      "sie/Sie": "scheinen",
    },
    präteritum: {
      ich: "schien",
      du: "schienst",
      "er/sie/es": "schien",
      wir: "schienen",
      ihr: "schient",
      "sie/Sie": "schienen",
    },
    partizip2: "geschienen",
    imperativ: { du: "schein", ihr: "scheint", Sie: "scheinen Sie" },
    zuInfinitiv: "zu scheinen",
  },

  erkennen: {
    lemma: "erkennen",
    aux: "haben",
    praesens: {
      ich: "erkenne",
      du: "erkennst",
      "er/sie/es": "erkennt",
      wir: "erkennen",
      ihr: "erkennt",
      "sie/Sie": "erkennen",
    },
    präteritum: {
      ich: "erkannte",
      du: "erkanntest",
      "er/sie/es": "erkannte",
      wir: "erkannten",
      ihr: "erkanntet",
      "sie/Sie": "erkannten",
    },
    partizip2: "erkannt",
    imperativ: { du: "erkenn", ihr: "erkennt", Sie: "erkennen Sie" },
    zuInfinitiv: "zu erkennen",
  },

  erstrecken: {
    lemma: "erstrecken",
    aux: "haben",
    praesens: {
      ich: "erstrecke",
      du: "erstreckst",
      "er/sie/es": "erstreckt",
      wir: "erstrecken",
      ihr: "erstreckt",
      "sie/Sie": "erstrecken",
    },
    präteritum: {
      ich: "erstreckte",
      du: "erstrecktest",
      "er/sie/es": "erstreckte",
      wir: "erstreckten",
      ihr: "erstrecktet",
      "sie/Sie": "erstreckten",
    },
    partizip2: "erstreckt",
    imperativ: { du: "erstreck", ihr: "erstreckt", Sie: "erstrecken Sie" },
    zuInfinitiv: "zu erstrecken",
  },

  abschließen: {
    lemma: "abschließen",
    aux: "haben",
    praesens: {
      ich: "schließe ab",
      du: "schließt ab",
      "er/sie/es": "schließt ab",
      wir: "schließen ab",
      ihr: "schließt ab",
      "sie/Sie": "schließen ab",
    },
    präteritum: {
      ich: "schloss ab",
      du: "schlossest ab",
      "er/sie/es": "schloss ab",
      wir: "schlossen ab",
      ihr: "schlosst ab",
      "sie/Sie": "schlossen ab",
    },
    partizip2: "abgeschlossen",
    imperativ: {
      du: "schließ ab",
      ihr: "schließt ab",
      Sie: "schließen Sie ab",
    },
    zuInfinitiv: "abzuschließen",
  },

  entwerfen: {
    lemma: "entwerfen",
    aux: "haben",
    praesens: {
      ich: "entwerfe",
      du: "entwirfst",
      "er/sie/es": "entwirft",
      wir: "entwerfen",
      ihr: "entwerft",
      "sie/Sie": "entwerfen",
    },
    präteritum: {
      ich: "entwarf",
      du: "entwarfst",
      "er/sie/es": "entwarf",
      wir: "entwarfen",
      ihr: "entwarft",
      "sie/Sie": "entwarfen",
    },
    partizip2: "entworfen",
    imperativ: { du: "entwirf", ihr: "entwerft", Sie: "entwerfen Sie" },
    zuInfinitiv: "zu entwerfen",
  },

  gewinnen: {
    lemma: "gewinnen",
    aux: "haben",
    praesens: { ich: "gewinne", du: "gewinnst", "er/sie/es": "gewinnt", wir: "gewinnen", ihr: "gewinnt", "sie/Sie": "gewinnen" },
    präteritum: { ich: "gewann", du: "gewannst", "er/sie/es": "gewann", wir: "gewannen", ihr: "gewannt", "sie/Sie": "gewannen" },
    partizip2: "gewonnen",
    imperativ: { du: "gewinn", ihr: "gewinnt", Sie: "gewinnen Sie" },
    zuInfinitiv: "zu gewinnen",
  },

  verschwinden: {
    lemma: "verschwinden",
    aux: "sein",
    praesens: { ich: "verschwinde", du: "verschwindest", "er/sie/es": "verschwindet", wir: "verschwinden", ihr: "verschwindet", "sie/Sie": "verschwinden" },
    präteritum: { ich: "verschwand", du: "verschwandest", "er/sie/es": "verschwand", wir: "verschwanden", ihr: "verschwandet", "sie/Sie": "verschwanden" },
    partizip2: "verschwunden",
    imperativ: { du: "verschwinde", ihr: "verschwindet", Sie: "verschwinden Sie" },
    zuInfinitiv: "zu verschwinden",
  },

  laufen: {
    lemma: "laufen",
    aux: "sein",
    praesens: { ich: "laufe", du: "läufst", "er/sie/es": "läuft", wir: "laufen", ihr: "lauft", "sie/Sie": "laufen" },
    präteritum: { ich: "lief", du: "liefst", "er/sie/es": "lief", wir: "liefen", ihr: "lieft", "sie/Sie": "liefen" },
    partizip2: "gelaufen",
    imperativ: { du: "lauf", ihr: "lauft", Sie: "laufen Sie" },
    zuInfinitiv: "zu laufen",
  },

  einsteigen: {
    lemma: "einsteigen",
    aux: "sein",
    praesens: { ich: "steige ein", du: "steigst ein", "er/sie/es": "steigt ein", wir: "steigen ein", ihr: "steigt ein", "sie/Sie": "steigen ein" },
    präteritum: { ich: "stieg ein", du: "stiegest ein", "er/sie/es": "stieg ein", wir: "stiegen ein", ihr: "stiegt ein", "sie/Sie": "stiegen ein" },
    partizip2: "eingestiegen",
    imperativ: { du: "steig ein", ihr: "steigt ein", Sie: "steigen Sie ein" },
    zuInfinitiv: "einzusteigen",
  },

  aufziehen: {
    lemma: "aufziehen",
    aux: "haben",
    praesens: { ich: "ziehe auf", du: "ziehst auf", "er/sie/es": "zieht auf", wir: "ziehen auf", ihr: "zieht auf", "sie/Sie": "ziehen auf" },
    präteritum: { ich: "zog auf", du: "zogst auf", "er/sie/es": "zog auf", wir: "zogen auf", ihr: "zogt auf", "sie/Sie": "zogen auf" },
    partizip2: "aufgezogen",
    imperativ: { du: "zieh auf", ihr: "zieht auf", Sie: "ziehen Sie auf" },
    zuInfinitiv: "aufzuziehen",
  },

  weiterspinnen: {
    lemma: "weiterspinnen",
    aux: "haben",
    praesens: { ich: "spinne weiter", du: "spinnst weiter", "er/sie/es": "spinnt weiter", wir: "spinnen weiter", ihr: "spinnt weiter", "sie/Sie": "spinnen weiter" },
    präteritum: { ich: "spann weiter", du: "spannst weiter", "er/sie/es": "spann weiter", wir: "spannen weiter", ihr: "spanntet weiter", "sie/Sie": "spannen weiter" },
    partizip2: "weitergesponnen",
    imperativ: { du: "spinn weiter", ihr: "spinnt weiter", Sie: "spinnen Sie weiter" },
    zuInfinitiv: "weiterzuspinnen",
  },

  behalten: {
    lemma: "behalten",
    aux: "haben",
    praesens: { ich: "behalte", du: "behältst", "er/sie/es": "behält", wir: "behalten", ihr: "behaltet", "sie/Sie": "behalten" },
    präteritum: { ich: "behielt", du: "behieltest", "er/sie/es": "behielt", wir: "behielten", ihr: "behieltet", "sie/Sie": "behielten" },
    partizip2: "behalten",
    imperativ: { du: "behalt", ihr: "behaltet", Sie: "behalten Sie" },
    zuInfinitiv: "zu behalten",
  },

  treffen: {
    lemma: "treffen",
    aux: "haben",
    praesens: { ich: "treffe", du: "triffst", "er/sie/es": "trifft", wir: "treffen", ihr: "trefft", "sie/Sie": "treffen" },
    präteritum: { ich: "traf", du: "trafst", "er/sie/es": "traf", wir: "trafen", ihr: "traft", "sie/Sie": "trafen" },
    partizip2: "getroffen",
    imperativ: { du: "triff", ihr: "trefft", Sie: "treffen Sie" },
    zuInfinitiv: "zu treffen",
  },

  finden: {
    lemma: "finden",
    aux: "haben",
    praesens: { ich: "finde", du: "findest", "er/sie/es": "findet", wir: "finden", ihr: "findet", "sie/Sie": "finden" },
    präteritum: { ich: "fand", du: "fandest", "er/sie/es": "fand", wir: "fanden", ihr: "fandet", "sie/Sie": "fanden" },
    partizip2: "gefunden",
    imperativ: { du: "find", ihr: "findet", Sie: "finden Sie" },
    zuInfinitiv: "zu finden",
  },

  greifen: {
    lemma: "greifen",
    aux: "haben",
    praesens: { ich: "greife", du: "greifst", "er/sie/es": "greift", wir: "greifen", ihr: "greift", "sie/Sie": "greifen" },
    präteritum: { ich: "griff", du: "griffst", "er/sie/es": "griff", wir: "griffen", ihr: "grifft", "sie/Sie": "griffen" },
    partizip2: "gegriffen",
    imperativ: { du: "greif", ihr: "greift", Sie: "greifen Sie" },
    zuInfinitiv: "zu greifen",
  },

  hängen: {
    lemma: "hängen",
    aux: "haben",
    praesens: { ich: "hänge", du: "hängst", "er/sie/es": "hängt", wir: "hängen", ihr: "hängt", "sie/Sie": "hängen" },
    präteritum: { ich: "hing", du: "hingst", "er/sie/es": "hing", wir: "hingen", ihr: "hingt", "sie/Sie": "hingen" },
    partizip2: "gehangen",
    imperativ: { du: "häng", ihr: "hängt", Sie: "hängen Sie" },
    zuInfinitiv: "zu hängen",
  },

  treten: {
    lemma: "treten",
    aux: "haben", // ver nota arriba
    praesens: { ich: "trete", du: "trittst", "er/sie/es": "tritt", wir: "treten", ihr: "tretet", "sie/Sie": "treten" },
    präteritum: { ich: "trat", du: "tratest", "er/sie/es": "trat", wir: "traten", ihr: "tratet", "sie/Sie": "traten" },
    partizip2: "getreten",
    imperativ: { du: "tritt", ihr: "tretet", Sie: "treten Sie" },
    zuInfinitiv: "zu treten",
  },

  begehen: {
    lemma: "begehen",
    aux: "haben",
    praesens: { ich: "begehe", du: "begehst", "er/sie/es": "begeht", wir: "begehen", ihr: "begeht", "sie/Sie": "begehen" },
    präteritum: { ich: "beging", du: "begingst", "er/sie/es": "beging", wir: "begingen", ihr: "begingt", "sie/Sie": "begingen" },
    partizip2: "begangen",
    imperativ: { du: "begeh", ihr: "begeht", Sie: "begehen Sie" },
    zuInfinitiv: "zu begehen",
  },

  vorliegen: {
    lemma: "vorliegen",
    aux: "haben",
    praesens: { ich: "liege vor", du: "liegst vor", "er/sie/es": "liegt vor", wir: "liegen vor", ihr: "liegt vor", "sie/Sie": "liegen vor" },
    präteritum: { ich: "lag vor", du: "lagst vor", "er/sie/es": "lag vor", wir: "lagen vor", ihr: "lagt vor", "sie/Sie": "lagen vor" },
    partizip2: "vorgelegen",
    imperativ: { du: "lieg vor", ihr: "liegt vor", Sie: "liegen Sie vor" },
    zuInfinitiv: "vorzuliegen",
  },

  // Opcional si quieres el base:
  hauen: {
    lemma: "hauen",
    aux: "haben",
    praesens: { ich: "haue", du: "haust", "er/sie/es": "haut", wir: "hauen", ihr: "haut", "sie/Sie": "hauen" },
    präteritum: { ich: "haute" /* también fuerte 'hieb' en estilo alto */, du: "hautest", "er/sie/es": "haute", wir: "hauten", ihr: "hautet", "sie/Sie": "hauten" },
    partizip2: "gehauen",
    imperativ: { du: "hau", ihr: "haut", Sie: "hauen Sie" },
    zuInfinitiv: "zu hauen",
  },

  klingen: {
    lemma: "klingen",
    aux: "haben",
    praesens: { ich: "klinge", du: "klingst", "er/sie/es": "klingt", wir: "klingen", ihr: "klingt", "sie/Sie": "klingen" },
    präteritum: { ich: "klang", du: "klangst", "er/sie/es": "klang", wir: "klangen", ihr: "klangt", "sie/Sie": "klangen" },
    partizip2: "geklungen",
    imperativ: { du: "kling", ihr: "klingt", Sie: "klingen Sie" },
    zuInfinitiv: "zu klingen",
  },

  halten: {
    lemma: "halten",
    aux: "haben",
    praesens: { ich: "halte", du: "hältst", "er/sie/es": "hält", wir: "halten", ihr: "haltet", "sie/Sie": "halten" },
    präteritum: { ich: "hielt", du: "hieltest", "er/sie/es": "hielt", wir: "hielten", ihr: "hieltet", "sie/Sie": "hielten" },
    partizip2: "gehalten",
    imperativ: { du: "halt", ihr: "haltet", Sie: "halten Sie" },
    zuInfinitiv: "zu halten",
  },
  denken: {
    lemma: "denken",
    aux: "haben",
    praesens: { ich: "denke", du: "denkst", "er/sie/es": "denkt", wir: "denken", ihr: "denkt", "sie/Sie": "denken" },
    präteritum: { ich: "dachte", du: "dachtest", "er/sie/es": "dachte", wir: "dachten", ihr: "dachtet", "sie/Sie": "dachten" },
    partizip2: "gedacht",
    imperativ: { du: "denk", ihr: "denkt", Sie: "denken Sie" },
    zuInfinitiv: "zu denken",
  },
  bringen: {
    lemma: "bringen",
    aux: "haben",
    praesens: { ich: "bringe", du: "bringst", "er/sie/es": "bringt", wir: "bringen", ihr: "bringt", "sie/Sie": "bringen" },
    präteritum: { ich: "brachte", du: "brachtest", "er/sie/es": "brachte", wir: "brachten", ihr: "brachtet", "sie/Sie": "brachten" },
    partizip2: "gebracht",
    imperativ: { du: "bring", ihr: "bringt", Sie: "bringen Sie" },
    zuInfinitiv: "zu bringen",
  },
  schlagen: {
    lemma: "schlagen",
    aux: "haben",
    praesens: { ich: "schlage", du: "schlägst", "er/sie/es": "schlägt", wir: "schlagen", ihr: "schlagt", "sie/Sie": "schlagen" },
    präteritum: { ich: "schlug", du: "schlugst", "er/sie/es": "schlug", wir: "schlugen", ihr: "schlagt", "sie/Sie": "schlugen" },
    partizip2: "geschlagen",
    imperativ: { du: "schlag", ihr: "schlagt", Sie: "schlagen Sie" },
    zuInfinitiv: "zu schlagen",
  },

  tun: {
    lemma: "tun",
    aux: "haben",
    praesens: { ich: "tue", du: "tust", "er/sie/es": "tut", wir: "tun", ihr: "tut", "sie/Sie": "tun" },
    präteritum: { ich: "tat", du: "tatest", "er/sie/es": "tat", wir: "taten", ihr: "tatet", "sie/Sie": "taten" },
    partizip2: "getan",
    imperativ: { du: "tu", ihr: "tut", Sie: "tun Sie" },
    zuInfinitiv: "zu tun",
  },

  erschaffen: {
    lemma: "erschaffen",
    aux: "haben",
    praesens: {
      ich: "erschaffe",
      du: "erschaffst",
      "er/sie/es": "erschafft",
      wir: "erschaffen",
      ihr: "erschafft",
      "sie/Sie": "erschaffen",
    },
    präteritum: {
      ich: "erschuf",
      du: "erschufst",
      "er/sie/es": "erschuf",
      wir: "erschufen",
      ihr: "erschuft",
      "sie/Sie": "erschufen",
    },
    partizip2: "erschaffen",
    imperativ: { du: "erschaff", ihr: "erschafft", Sie: "erschaffen Sie" },
    zuInfinitiv: "zu erschaffen",
  },

  kennen: {
    lemma: "kennen",
    aux: "haben",
    praesens: { ich: "kenne", du: "kennst", "er/sie/es": "kennt", wir: "kennen", ihr: "kennt", "sie/Sie": "kennen" },
    präteritum: { ich: "kannte", du: "kanntest", "er/sie/es": "kannte", wir: "kannten", ihr: "kanntet", "sie/Sie": "kannten" },
    partizip2: "gekannt",
    imperativ: { du: "kenn", ihr: "kennt", Sie: "kennen Sie" },
    zuInfinitiv: "zu kennen",
  },

  tragen: {
    lemma: "tragen",
    aux: "haben",
    praesens: { ich: "trage", du: "trägst", "er/sie/es": "trägt", wir: "tragen", ihr: "tragt", "sie/Sie": "tragen" },
    präteritum: { ich: "trug", du: "trugst", "er/sie/es": "trug", wir: "trugen", ihr: "trugt", "sie/Sie": "trugen" },
    partizip2: "getragen",
    imperativ: { du: "trag", ihr: "tragt", Sie: "tragen Sie" },
    zuInfinitiv: "zu tragen",
  },

  fallen: {
    lemma: "fallen",
    aux: "sein",
    praesens: { ich: "falle", du: "fällst", "er/sie/es": "fällt", wir: "fallen", ihr: "fallt", "sie/Sie": "fallen" },
    präteritum: { ich: "fiel", du: "fielst", "er/sie/es": "fiel", wir: "fielen", ihr: "fielt", "sie/Sie": "fielen" },
    partizip2: "gefallen", // ojo: homógrafo de 'gefallen' (gustar)
    imperativ: { du: "fall", ihr: "fallt", Sie: "fallen Sie" },
    zuInfinitiv: "zu fallen",
  },

  ziehen: {
    lemma: "ziehen",
    aux: "haben", // Nota: en uso intransitivo de movimiento (z.B. 'nach Berlin ziehen') se usa a menudo 'sein'
    praesens: { ich: "ziehe", du: "ziehst", "er/sie/es": "zieht", wir: "ziehen", ihr: "zieht", "sie/Sie": "ziehen" },
    präteritum: { ich: "zog", du: "zogst", "er/sie/es": "zog", wir: "zogen", ihr: "zogt", "sie/Sie": "zogen" },
    partizip2: "gezogen",
    imperativ: { du: "zieh", ihr: "zieht", Sie: "ziehen Sie" },
    zuInfinitiv: "zu ziehen",
  },

  befinden: {
    lemma: "befinden",
    aux: "haben",
    praesens: { ich: "befinde", du: "befindest", "er/sie/es": "befindet", wir: "befinden", ihr: "befindet", "sie/Sie": "befinden" },
    präteritum: { ich: "befand", du: "befandest", "er/sie/es": "befand", wir: "befanden", ihr: "befandet", "sie/Sie": "befanden" },
    partizip2: "befunden",
    imperativ: { du: "befinde", ihr: "befindet", Sie: "befinden Sie" },
    zuInfinitiv: "zu befinden",
  },

  umschließen: {
    lemma: "umschließen",
    aux: "haben",
    praesens: { ich: "umschließe", du: "umschließt", "er/sie/es": "umschließt", wir: "umschließen", ihr: "umschließt", "sie/Sie": "umschließen" },
    präteritum: { ich: "umschloss", du: "umschlossest", "er/sie/es": "umschloss", wir: "umschlossen", ihr: "umschlosst", "sie/Sie": "umschlossen" },
    partizip2: "umschlossen",
    imperativ: { du: "umschließ", ihr: "umschließt", Sie: "umschließen Sie" },
    zuInfinitiv: "zu umschließen",
  },
};
