// WordTypes.js - Versión mejorada con más palabras capturadas

// === ARTÍCULOS ===
export const articles = [
  "der",
  "die",
  "das",
  "ein",
  "eine",
  "einer",
  "einem",
  "einen",
  "den",
  "dem",
  "des",
  "im",
  "ins",
  "am",
  "ans",
  "vom",
  "zum",
  "zur",
  "aufs", // auf + das
  "durchs", // durch + das
  "fürs", // für + das
  "ums", // um + das
  "übers", // über + das
  "unters", // unter + das
  "hinters", // hinter + das
  "vors", // vor + das
  "neben", // puede ser preposición o artículo contracto
];

// === PREPOSICIONES ===
export const prepositions = [
  "in",
  "auf",
  "mit",
  "zu",
  "von",
  "für",
  "an",
  "bei",
  "nach",
  "über",
  "unter",
  "vor",
  "hinter",
  "zwischen",
  "neben",
  "durch",
  "ohne",
  "gegen",
  "um",
  "bis",
  "seit",
  "während",
  "trotz",
  "wegen",
  "statt",
  "außer",
  "binnen",
  "dank",
  "laut",
  "samt",
  "nebst",
  "entlang",
  "gegenüber",
  "innerhalb",
  "außerhalb",
  "oberhalb",
  "unterhalb",
  "diesseits",
  "jenseits",
  "beiderseits",
  "abseits",
  "anstelle",
  "anstatt",
  "mittels",
  "kraft",
  "mangels",
  "zwecks",
  "hinsichtlich",
  "bezüglich",
  "angesichts",
  "aufgrund",
  "infolge",
  "zufolge",
  "zugunsten",
  "zulasten",
  "am",
  "aus",
  "ab",
];

// === PRONOMBRES ===
export const pronouns = [
  "ich",
  "du",
  "er",
  "sie",
  "es",
  "wir",
  "ihr",
  "mich",
  "dich",
  "ihn",
  "uns",
  "euch",
  "mir",
  "dir",
  "ihm",
  "ihnen",
  "mein",
  "dein",
  "sein",
  "ihre",
  "unser",
  "euer",
  "meine",
  "seine",
  "unsere",
  "eure",
  "diesem",
  "dieser",
  "dieses",
  "jener",
  "jene",
  "jenes",
  "welcher",
  "welche",
  "welches",
  "man",
  "sich",
  "meiner",
  "deiner",
  "seiner",
  "ihrer",
  "unserer",
  "eurer",
  "meinen",
  "deinen",
  "seinen",
  "ihren",
  "unseren",
  "euren",
  "meinem",
  "deinem",
  "seinem",
  "ihrem",
  "unserem",
  "eurem",
  "keine",
  "keiner",
  "keinem",
  "keinen",
  "diese",
  "wo",
  "was",
  "wie",
  "einige",
  "viele",
  "solche",
  "alle",
  "jeder",
  "jede",
  "jedes",
  "mancher",
  "manche",
  "manches",
  "diesen",
  "jeden",
  "jemand",
  "jemandem",
  "deine",
  "andere",
  "verschiedene",
  "dabei",
  "mal",
  "irgendetwas",
  "etwas",
  "nichts",
  "alles",
  "wenig",
  "viel",
];

// === CONJUNCIONES ===
export const conjunctions = [
  "und",
  "oder",
  "aber",
  "denn",
  "sondern",
  "doch",
  "so",
  "dass",
  "weil",
  "ob",
  "wenn",
  "als",
  "bevor",
  "nachdem",
  "bis",
  "seit",
  "sobald",
  "solange",
  "falls",
  "sofern",
  "obwohl",
  "während",
  "ehe",
  "indem",
  "damit",
  "sodass",
  "zumal",
  "obgleich",
  "obschon",
  "entweder",
  "weder",
  "sowohl",
  "nicht",
  "zwar",
  "jedoch",
  "trotzdem",
  "dennoch",
  "außerdem",
  "übrigens",
  "allerdings",
  "freilich",
  "jedenfalls",
  "immerhin",
  "hingegen",
  "dagegen",
  "vielmehr",
  "nämlich",
  "deshalb",
  "daher",
  "folglich",
  "somit",
  "also",
];

// === ADVERBIOS ===
export const adverbs = [
  "hier",
  "dort",
  "da",
  "sehr",
  "auch",
  "noch",
  "schon",
  "nur",
  "immer",
  "nie",
  "oft",
  "manchmal",
  "heute",
  "gestern",
  "morgen",
  "jetzt",
  "dann",
  "danach",
  "vorher",
  "gerne",
  "gern",
  "vielleicht",
  "wahrscheinlich",
  "sicher",
  "bestimmt",
  "fast",
  "etwa",
  "ungefähr",
  "ziemlich",
  "völlig",
  "ganz",
  "halb",
  "etwas",
  "nichts",
  "alles",
  "wenig",
  "viel",
  "mehr",
  "weniger",
  "genug",
  "zurück",
  "weg",
  "her",
  "hin",
  "raus",
  "rein",
  "hoch",
  "runter",
  "links",
  "rechts",
  "geradeaus",
  "überall",
  "nirgends",
  "irgendwo",
  "anderswo",
  "zusammen",
  "allein",
  "gemeinsam",
  "einzeln",
  "plötzlich",
  "langsam",
  "schnell",
  "leise",
  "laut",
  "ruhig",
  "aufmerksam",
  "freundlich",
  "direkt",
  "besonders",
  "relativ",
  "absolut",
  "teilweise",
  "richtig",
  "falsch",
  "wirklich",
  "tatsächlich",
  "eigentlich",
  "hauptsächlich",
  "normalerweise",
  "üblicherweise",
  "meistens",
  "selten",
  "kaum",
  "ebenfalls",
  "zusätzlich",
  "weiterhin",
  "bereits",
  "schließlich",
  "endlich",
  "sofort",
  "gleich",
  "bald",
  "spät",
  "früh",
  "pünktlich",
  "rechtzeitig",
  "verspätet",
  "verfrüht",
  "vorne",
  "hinten",
  "behutsam",
  "genau",
  "total",
  "echt",
  "klar",
  "definitiv",
  "angenehm",
  "flexibel",
  "irgendwie",
  "eher",
  "na",
  "oh",
  "ja",
  "nein",
  "eben",
  "quasi",
  "nochmal",
  "weiter",
  "daraus",
  "damals",
  "darum",
  "wiederum",
  "super",
  "danke",
  "vorn",
  "genauso",
  "darauf",
  "anders",
  "hm",
  "ok",
  "daran",
  "wann",
  "woher",
  "gerade",
  "whenever", // anglicismo común
];

// === SUSTANTIVOS COMUNES ===
export const commonNouns = [
  // Personas y familia
  "frau",
  "mann",
  "hund",
  "katze",
  "kind",
  "mensch",
  "person",
  "leute",
  "familie",
  "personen",
  "zeigefinger",
  "gesichtsausdruck",
  "mund",
  "ohr",
  "kopf",
  "schultern",
  "hand",
  "haare",
  "blick",
  "richtung",
  "haaren",
  "körper",
  "körperteil",
  "zähne",
  "mundwinkel",
  "mimik",

  // Casa y objetos
  "haus",
  "wohnung",
  "zimmer",
  "küche",
  "bad",
  "garten",
  "straße",
  "stadt",
  "land",
  "welt",
  "tisch",
  "stuhl",
  "bett",
  "schrank",
  "fenster",
  "tür",
  "wand",
  "decke",
  "boden",
  "sofa",
  "sessel",
  "wohnzimmer",
  "leseecke",
  "bücher",
  "esszimmer",
  "tasse",
  "tassen",
  "kissen",
  "untergrund",
  "originalfoto",
  "vorlage",
  "entwurf",
  "glas",
  "druck",

  // Ropa y accesorios
  "jacke",
  "hemd",
  "hose",
  "kleid",
  "rock",
  "bluse",
  "pullover",
  "mantel",
  "schuhe",
  "socken",
  "strümpfe",
  "unterwäsche",
  "hut",
  "mütze",
  "brille",
  "uhr",
  "ring",
  "kette",
  "ohrringe",
  "tasche",
  "koffer",
  "rucksack",
  "geldbörse",
  "oberteil",
  "absatzschuhe",
  "umhängetasche",
  "streifen",
  "gurt",
  "knoten",
  "fell",

  // Conceptos abstractos y otros
  "zeit",
  "jahr",
  "monat",
  "woche",
  "tag",
  "stunde",
  "minute",
  "sekunde",
  "morgen",
  "mittag",
  "abend",
  "nacht",
  "leben",
  "tod",
  "geburt",
  "alter",
  "jugend",
  "kindheit",
  "atmosphäre",
  "gefühl",
  "eindruck",
  "ausdruck",
  "adjektiv",
  "look",
  "beispiel",
  "grunde",
  "rand",
  "frage",
  "wörter",
  "paar",
  "fall",
  "wort",
  "moment",
  "art",
  "szenarien",
  "möglichkeiten",
  "lichtstrahlen",
  "unkraut",
  "papier",
  "linie",
  "symbol",
  "beispiele",
  "prinzip",
  "spaß",
  "fotografie",
  "version",
  "oberkörper",
  "stirn",
  "gefühle",
  "video",
  "skizze",
  "zeichner",
  "kohle",
  "farbe",
  "baupläne",
  "frisur",
  "freude",
  "wärme",
  "maß",
  "bias",
  "ruhe",
  "sache",
  "ende",
  "freunden",
  "hintergrund",
  "szene",
  "bild",
  "foto",
  "zeichnung",
  "comic",
  "farbfläche",
  "zottel",
  "haarbüschel",
  "fellbüschel",
  "wettbewerb",
  "figur",
  "herzsymbol",
  "wortes",
  "sinne",
  "gesichtsausdrücke",
  "hootsum",
];

// === VERBOS EN INFINITIVO Y CONJUGADOS ===
export const infinitiveVerbs = [
  "sein",
  "haben",
  "werden",
  "können",
  "müssen",
  "sollen",
  "wollen",
  "dürfen",
  "mögen",
  "lassen",
  "gehen",
  "kommen",
  "sehen",
  "hören",
  "sagen",
  "machen",
  "tun",
  "geben",
  "nehmen",
  "bringen",
  "holen",
  "finden",
  "suchen",
  "kaufen",
  "verkaufen",
  "arbeiten",
  "spielen",
  "lernen",
  "studieren",
  "lehren",
  "zeigen",
  "erklären",
  "verstehen",
  "wissen",
  "denken",
  "glauben",
  "meinen",
  "hoffen",
  "wünschen",
  "träumen",
  "schlafen",
  "aufstehen",
  "aufwachen",
  "anziehen",
  "ausziehen",
  "waschen",
  "duschen",
  "baden",
  "kämmen",
  "rasieren",
  "schminken",
  "essen",
  "trinken",
  "kochen",
  "backen",
  "schneiden",
  "rühren",
  "mischen",
  "würzen",
  "probieren",
  "schmecken",
  "riechen",
  "fühlen",
  "berühren",
  "streicheln",
  "küssen",
  "umarmen",
  "lieben",
  "hassen",
  "gefallen",
  "freuen",
  "ärgern",
  "trauern",
  "weinen",
  "lachen",
  "lächeln",
  "sprechen",
  "reden",
  "erzählen",
  "fragen",
  "antworten",
  "rufen",
  "schreien",
  "flüstern",
  "singen",
  "pfeifen",
  "zuhören",
  "lauschen",
  "schauen",
  "blicken",
  "starren",
  "beobachten",
  "betrachten",
  "ansehen",
  "lesen",
  "schreiben",
  "zeichnen",
  "malen",
  "fotografieren",
  "filmen",
  "tanzen",
  "musizieren",
  "reisen",
  "fahren",
  "fliegen",
  "schwimmen",
  "laufen",
  "rennen",
  "springen",
  "klettern",
  "wandern",
  "spazieren",
  "joggen",
  "radfahren",
  "reiten",
  "segeln",
  "genieße",
  "finde",
  "mach",
  "helfen",
  "abwaschen",
  "nennen",
  "freuen",
  "kennen",
  "zerlegen",
  "zeichnen",
  "sprechen",
  "geben",
  "bescheid",
];

// === ADJETIVOS BÁSICOS Y DECLINADOS ===
export const basicAdjectives = [
  // Colores
  "rot",
  "blau",
  "grün",
  "gelb",
  "schwarz",
  "weiß",
  "braun",
  "grau",
  "rosa",
  "orange",
  "violett",
  "lila",

  // Tamaños
  "groß",
  "klein",
  "lang",
  "kurz",
  "hoch",
  "niedrig",
  "breit",
  "schmal",
  "dick",
  "dünn",
  "mittelgroß",
  "dünnen",
  "dicken",
  "dickere",
  "kürzere",

  // Cualidades básicas
  "gut",
  "schlecht",
  "neu",
  "alt",
  "jung",
  "leicht",
  "schwer",
  "hell",
  "dunkel",
  "schön",
  "einfach",
  "perfekt",
  "angenehm",
  "bequem",
  "gemütlich",
  "heimelig",
  "kuschelig",
  "einladend",
  "sonnig",
  "spannend",
  "bildhafter",
  "unordentliche",
  "struppigem",
  "wuschelige",
  "zottelige",
  "zotteliges",
  "schlicht",
  "entspannt",
  "schief",
  "warm",
  "wuscheligen",
  "zerzaust",
  "zerzauste",
  "aufgeräumt",
  "bildhaft",
  "ganz",
  "einfache",
  "technische",
  "unsichtbare",
  "visuelles",
  "einfaches",
  "einzelne",
  "ganze",
  "besonderer",
  "überraschter",
  "typische",
  "positive",
  "mittleres",
  "wild",
  "wilde",
  "soziales",
  "visuelle",
  "eigene",

  // Estados
  "müde",
  "wach",
  "hungrig",
  "satt",
  "durstig",
  "glücklich",
  "traurig",
  "fröhlich",
  "ernst",
  "ruhig",
  "nervös",
  "ängstlich",
  "mutig",
  "sicher",
  "unsicher",
];

export const declinedAdjectives = [
  // Formas declinadas de adjetivos comunes
  "kleine",
  "kleinen",
  "kleiner",
  "kleines",
  "große",
  "großen",
  "großer",
  "großes",
  "lange",
  "langen",
  "langer",
  "langes",
  "kurze",
  "kurzen",
  "kurzer",
  "kurzes",
  "neue",
  "neuen",
  "neuer",
  "neues",
  "alte",
  "alten",
  "alter",
  "altes",
  "junge",
  "jungen",
  "junger",
  "junges",
  "gute",
  "guten",
  "guter",
  "gutes",
  "schlechte",
  "schlechten",
  "schlechter",
  "schlechtes",
  "schöne",
  "schönen",
  "schöner",
  "schönes",
  "gemütliche",
  "gemütliches",
  "einladende",
  "bequeme",
  "mögliche",
  "voller",
  "knielangen",
  "dunkelblauen",
  "langärmeliges",
  "hellblaues",
  "oberste",
  "gewellte",
  "graues",
  "rechten",
  "linken",
  "zotteligem",
  "beide",
  "beiden",
  "warme",
  "glücklichen",
  "traurigen",
  "fröhlichen",
  "lustigen",
  "ernsten",
  "ruhigen",
  "unruhigen",
  "nervösen",
  "entspannten",
  "gestressten",
  "ängstlichen",
  "mutigen",
  "vorsichtigen",
  "gefährlichen",
  "sicheren",
  "unsicheren",
  "einfachen",
  "schwierigen",
  "komplizierten",
  "wichtigen",
  "unwichtigen",
  "interessanten",
  "langweiligen",
  "spannenden",
  "aufregenden",
  "beruhigenden",
  "gemütlichen",
  "einladenden",
  "bequemen",
  "zerzausten",
  "ganzen",
  "zerbrechliches",
  "fröhliches",
  "tägliches",
];

export const adjectivesEndingInT = [
  "alt",
  "fest",
  "hart",
  "kalt",
  "kurz",
  "lang",
  "neu",
  "jung",
  "gut",
  "schlecht",
  "groß",
  "klein",
  "hoch",
  "niedrig",
  "breit",
  "schmal",
  "dick",
  "dünn",
  "schwer",
  "leicht",
  "stark",
  "schwach",
  "schnell",
  "langsam",
  "heiß",
  "warm",
  "kühl",
  "hell",
  "dunkel",
  "laut",
  "leise",
  "süß",
  "sauer",
  "bitter",
  "scharf",
  "mild",
  "spät",
  "früh",
  "tot",
  "lebendig",
  "wert",
  "unwert",
  "recht",
  "unrecht",
  "echt",
  "falsch",
  "richtig",
  "wahr",
  "unwahr",
  "direkt",
  "indirekt",
  "perfekt",
  "imperfekt",
  "komplett",
  "inkomplett",
  "konkret",
  "abstrakt",
  "exakt",
  "inexakt",
  "intakt",
  "defekt",
  "korrekt",
  "inkorrekt",
];

export const adjectivesEndingInEn = [
  "kleinen",
  "großen",
  "langen",
  "kurzen",
  "neuen",
  "alten",
  "jungen",
  "guten",
  "schlechten",
  "schönen",
  "hässlichen",
  "hohen",
  "niedrigen",
  "breiten",
  "schmalen",
  "dicken",
  "dünnen",
  "schweren",
  "leichten",
  "starken",
  "schwachen",
  "schnellen",
  "langsamen",
  "heißen",
  "kalten",
  "warmen",
  "kühlen",
  "hellen",
  "dunklen",
  "lauten",
  "leisen",
  "süßen",
  "sauren",
  "bitteren",
  "scharfen",
  "milden",
  "roten",
  "blauen",
  "grünen",
  "gelben",
  "schwarzen",
  "weißen",
  "braunen",
  "grauen",
  "freundlichen",
  "unfreundlichen",
  "höflichen",
  "unhöflichen",
  "netten",
  "gemeinen",
  "lieben",
  "bösen",
  "klugen",
  "dummen",
  "intelligenten",
  "fleißigen",
  "faulen",
  "reichen",
  "armen",
  "gesunden",
  "kranken",
  "müden",
  "wachen",
  "hungrigen",
  "satten",
  "durstigen",
  "glücklichen",
  "traurigen",
  "fröhlichen",
  "lustigen",
  "ernsten",
  "ruhigen",
  "unruhigen",
  "nervösen",
  "entspannten",
  "gestressten",
  "ängstlichen",
  "mutigen",
  "vorsichtigen",
  "gefährlichen",
  "sicheren",
  "unsicheren",
  "einfachen",
  "schwierigen",
  "komplizierten",
  "wichtigen",
  "unwichtigen",
  "interessanten",
  "langweiligen",
  "spannenden",
  "aufregenden",
  "beruhigenden",
  "gemütlichen",
  "einladenden",
  "bequemen",
  "zerzausten",
  "ganzen",
];

// Casos especiales finales
export const specialCases = {
  // Números
  null: "number",
  eins: "number",
  zwei: "number",
  drei: "number",
  vier: "number",
  fünf: "number",
  sechs: "number",
  sieben: "number",
  acht: "number",
  neun: "number",
  zehn: "number",
  elf: "number",
  zwölf: "number",
  dreizehn: "number",
  vierzehn: "number",
  fünfzehn: "number",
  sechzehn: "number",
  siebzehn: "number",
  achtzehn: "number",
  neunzehn: "number",
  zwanzig: "number",
  dreißig: "number",
  vierzig: "number",
  fünfzig: "number",
  sechzig: "number",
  siebzig: "number",
  achtzig: "number",
  neunzig: "number",
  hundert: "number",
  tausend: "number",
  million: "number",
  milliarde: "number",
  erste: "number",
  zweite: "number",
  dritte: "number",

  // Verbos conjugados específicos
  ist: "verb",
  sind: "verb",
  war: "verb",
  waren: "verb",
  bin: "verb",
  bist: "verb",
  hat: "verb",
  haben: "verb",
  hatte: "verb",
  hatten: "verb",
  wird: "verb",
  werden: "verb",
  wurde: "verb",
  wurden: "verb",
  kann: "verb",
  können: "verb",
  konnte: "verb",
  konnten: "verb",
  will: "verb",
  wollen: "verb",
  wollte: "verb",
  wollten: "verb",
  soll: "verb",
  sollen: "verb",
  sollte: "verb",
  sollten: "verb",
  muss: "verb",
  müssen: "verb",
  musste: "verb",
  mussten: "verb",
  darf: "verb",
  dürfen: "verb",
  durfte: "verb",
  durften: "verb",
  mag: "verb",
  mögen: "verb",
  mochte: "verb",
  mochten: "verb",
  möchte: "verb",
  möchten: "verb",

  // Palabras especiales alemanas
  wäre: "verb", // sería (subjuntivo de sein)
  lass: "verb", // deja (imperativo de lassen)
  hab: "verb", // tengo (coloquial de haben)
  gab: "verb", // había/hubo (pretérito de geben)
  würde: "verb", // haría (subjuntivo de werden)
  gebe: "verb", // doy (1ra persona de geben)
  wasche: "verb", // lavo (1ra persona de waschen)
  gucke: "verb", // miro (1ra persona de gucken)
  schaue: "verb", // miro (1ra persona de schauen)
  zeichne: "verb", // dibujo (1ra persona de zeichnen)
  habe: "verb", // tengo (1ra persona de haben)
  kenne: "verb", // conozco (1ra persona de kennen)
  helfe: "verb", // ayudo (1ra persona de helfen)
  abwasche: "verb", // lavo platos (1ra persona de abwaschen)
  mache: "verb", // hago (1ra persona de machen)
  nenne: "verb", // nombro (1ra persona de nennen)
  freue: "verb", // me alegro (1ra persona de freuen)
  zerleg: "verb", // descompongo (forma coloquial)
  zeich: "verb", // dibujo (forma abreviada)
  sprich: "verb", // hablo (imperativo de sprechen)
  geb: "verb", // doy (forma coloquial)
  sag: "verb", // digo (imperativo de sagen)

  // Partículas y otras
  bitte: "other",
  danke: "adverb",
  bescheid: "noun", // "Bescheid" es sustantivo, como en "Bescheid geben/sagen"
  zeihhan: "foreign", // error de transcripción
  zeihanon: "foreign", // error de transcripción
  any: "foreign", // palabra inglesa
};

export const ambiguousWords = {
  wolle: {
    type: "ambiguous",
    meanings: "lana (sustantivo) / quería (verbo)",
    primary: "noun",
  },
};
