import { SUPPLETIVE_COMPARATIVES, SUPPLETIVE_SUPERLATIVES } from "./superlatives.js";
import { ADJECTIVES_EMOTIONS } from "./emotions.js";
import { ADJECTIVES_LANGUAGE } from "./language.js";
import { ADJECTIVES_PARTICIPLES } from "./participles.js";
import { ADJECTIVES_POSITION } from "./position.js";
import { ADJECTIVES_SENSES } from "./senses.js";
import { ADJECTIVES_SIZE } from "./size.js";
import { ADJECTIVES_SOCIAL } from "./social.js";
import { ADJECTIVES_SPACE } from "./space.js";
import { ADJECTIVES_TIME } from "./time.js";
import {
  ADJECTIVE_DECLINATIONS,
  APPEARANCE_GENERAL,
  APPEARANCE_STYLE,
  COLORS,
  EVALUATION_FORMS,
  AGE_FORMS,
  DIFFICULTY_FORMS,
  BRIGHTNESS_FORMS,
  TEMPERATURE_FORMS,
  NATURE_TECH_FORMS,
  VISIBILITY_FORMS,
  IMPORTANCE_MODALITY_FORMS,
  SPECIFICITY_FORMS,
  CONDITION_FORMS,
  VALUE_FORMS,
} from "./quality.js";

export const ADJECTIVES = [
  ...ADJECTIVES_EMOTIONS,
  ...ADJECTIVES_LANGUAGE,
  ...ADJECTIVES_PARTICIPLES,
  ...ADJECTIVES_POSITION,
  ...ADJECTIVES_SENSES,
  ...ADJECTIVES_SIZE,
  ...ADJECTIVES_SOCIAL,
  ...ADJECTIVES_SPACE,
  ...ADJECTIVES_TIME,
  ...ADJECTIVE_DECLINATIONS,
  ...AGE_FORMS,
  ...APPEARANCE_GENERAL,
  ...APPEARANCE_STYLE,
  ...BRIGHTNESS_FORMS,
  ...COLORS,
  ...CONDITION_FORMS,
  ...DIFFICULTY_FORMS,
  ...EVALUATION_FORMS,
  ...IMPORTANCE_MODALITY_FORMS,
  ...NATURE_TECH_FORMS,
  ...SPECIFICITY_FORMS,
  ...SUPPLETIVE_COMPARATIVES,
  ...SUPPLETIVE_SUPERLATIVES,
  ...TEMPERATURE_FORMS,
  ...VALUE_FORMS,
  ...VISIBILITY_FORMS,
].sort((a, b) => (a.de < b.de ? -1 : 1));
