import { flatteAdj } from "../utils/builders.js";

export const ADJECTIVES_PARTICIPLES_FORMS = [
  { base: { de: "ausgerichtet", es: "orientado/a" } },
  { base: { de: "gekämmt", es: "peinado/a" }, gradable: false },
  { base: { de: "proportioniert", es: "proporcionado/a" } },
  { base: { de: "ausgeprägt", es: "marcado/a" } },
  { base: { de: "geöffnet", es: "abierto/a" } },
  { base: { de: "geschlossen", es: "cerrado/a" }, gradable: false },
  { base: { de: "aufgenommen", es: "grabado" }, gradable: false },
  { base: { de: "geordnet", es: "ordenado/a" }, gradable: false },
  { base: { de: "gelungen", es: "logrado" }, gradable: false },
  { base: { de: "verheiratet", es: "casado/a" }, gradable: false },
  { base: { de: "bekannt", es: "conocido/a" }, gradable: false },
  { base: { de: "interessiert", es: "interesado/a" }, gradable: false },
  { base: { de: "überzogen", es: "exagerado/a" } },
  { base: { de: "kommentiert", es: "comentado/a" }, gradable: false },
  { base: { de: "strukturiert", es: "estructurado/a" } },
  { base: { de: "fertig", es: "terminado/a" } },
  { base: { de: "beschimpfend", es: "injuriante" } },
  { base: { de: "geschützt", es: "protegido/a" } },
  { base: { de: "betroffen", es: "afectado/a" } },
  { base: { de: "ausgedacht", es: "inventado/a" } },
  { base: { de: "angezeigt", es: "indicado, mostrado" } },
  { base: { de: "betrieben", es: "gestionado, operado" } },
  { base: { de: "befunden", es: "considerado" } },
  { base: { de: "bestraft", es: "castigado" } },
  { base: { de: "zusammengetragen", es: "recopilado" } },
  { base: { de: "ausgeschieden", es: "eliminado/a" }, gradable: false },
  { base: { de: "abgeräumt", es: "recogido/a" }, gradable: false },
  { base: { de: "verschätzt", es: "mal calculado/a" }, gradable: false },
  { base: { de: "überflutet", es: "inundado/a" }, gradable: false },
  { base: { de: "geklappt", es: "plegado/a" }, gradable: false },
  { base: { de: "aufgemacht", es: "abierto/a" }, gradable: false },
  { base: { de: "gelandet", es: "aterrizado/a" }, gradable: false },
];

export const ADJECTIVES_PARTICIPLES = flatteAdj(ADJECTIVES_PARTICIPLES_FORMS);
