export const ADV_PLACE = [
  "hier",
  "dort",
  "da",
  "überall",
  "nirgends",
  "irgendwo",
  "anderswo",
  "links",
  "rechts",
  "geradeaus",
  "vorne",
  "vorn",
  "hinten",
  "rein",
  "raus",
  "hoch",
  "runter",
  "zurück",
  "weg",
  "her",
  "hin",
  "daran",
  "darauf",
  "daraus",
  "dorthin",
  "hinauf",
  "hinaus",
  "hinunter",
  "draußen",
  "drinnen",
  "hinüber",
  "herüber",
  "dahin",
  "hinein",
  "heraus",
];

export const ADV_TIME = [
  "heute",
  "gestern",
  "morgen",
  "jetzt",
  "damals",
  "dann",
  "danach",
  "vorher",
  "zuvor",
  "bald",
  "schon",
  "noch",
  "bereits",
  "endlich",
  "schließlich",
  "sofort",
  "gleich",
  "spät",
  "früh",
  "pünktlich",
  "rechtzeitig",
  "verspätet",
  "verfrüht",
  "immer",
  "nie",
  "oft",
  "manchmal",
  "meistens",
  "selten",
  "nachts",
  "zweimal",
  "einmal",
  "später",
  "früher",
  "erst",
  "wieder",
];

export const ADV_MANNER = [
  "gern",
  "gerne",
  "schnell",
  "langsam",
  "leise",
  "laut",
  "ruhig",
  "aufmerksam",
  "freundlich",
  "behutsam",
  "direkt",
  "zusammen",
  "gemeinsam",
  "allein",
  "einzeln",
  "plötzlich",
  "anders",
  "genauso",
  "irgendwie",
  "unnötig",
  "flexibel",
  "angenehm",
  "recht",
  "weiter",
  "lieber",
  "fertig",
];

export const ADV_DEGREE = [
  "sehr",
  "ziemlich",
  "völlig",
  "ganz",
  "halb",
  "etwas",
  "mehr",
  "weniger",
  "genug",
  "fast",
  "kaum",
  "total",
  "echt",
  "absolut",
  "relativ",
  "besonders",
  "teilweise",
  "wirklich",
  "tatsächlich",
  "hauptsächlich",
  "normalerweise",
  "üblicherweise",
  "viel",
  "wenig",
  "etwa",
  "eher",
  "auch",
  "nicht",
];

export const ADV_MODALITY = ["wahrscheinlich", "vielleicht", "sicher", "bestimmt", "definitiv", "klar", "eigentlich", "wohl"];

export const ADV_CONNECTIVE = [
  "dann",
  "darum",
  "wiederum",
  "ebenso",
  "ebenfalls",
  "zusätzlich",
  "weiterhin",
  "außerdem",
  "schließlich",
  "immerhin",
  "zwar",
  "jedoch",
  "allerdings",
  "übrigens",
  "nämlich",
  "quasi",
  "eben",
  "doch",
  "so",
  "also",
];

export const ADV_PARTICLES = ["ja", "nein", "oh", "hm", "ok", "na", "super", "danke", "mal"];

export const BLOCKS_ADVERBS = {
  PLACE: ADV_PLACE,
  TIME: ADV_TIME,
  MANNER: ADV_MANNER,
  DEGREE: ADV_DEGREE,
  MODALITY: ADV_MODALITY,
  CONNECTIVE: ADV_CONNECTIVE,
  PARTICLES: ADV_PARTICLES,
};

export const ADVERBS = Array.from(new Set([...ADV_PLACE, ...ADV_TIME, ...ADV_MANNER, ...ADV_DEGREE, ...ADV_MODALITY, ...ADV_CONNECTIVE, ...ADV_PARTICLES]));

export const IRREGULAR_ADVERBS = [
  "gern",
  "gerne",
  "kaum",
  "schon",
  "eben",
  "mal",
  "wohl",
  "etwa",
  "fast",
  "ziemlich",
  "ganz",
  "recht",
  "eher",
  "doch",
  "ja",
  "nein",
  "später",
  "früher",
  "wieder",
  "erst",
  "auch",
  "nicht",
  "weiter",
  "lieber",
  "fertig",
  "hinein",
  "heraus",
  "dorthin",
  "hinauf",
  "hinaus",
  "hinunter",
  "draußen",
  "drinnen",
  "hinüber",
  "herüber",
  "dahin",
];

export const isAdverb = (word) => ADVERBS.includes(String(word).toLowerCase());

export const isIrregularAdverb = (word) => IRREGULAR_ADVERBS.includes(String(word).toLowerCase());
