export const WORD_TYPES = {
  ADJECTIVE: { id: "adjective", color: "#ff9500", emoji: "🟠", label: "adjetivo" },
  ADVERB: { id: "adverb", color: "#8a2be2", emoji: "🟪", label: "adverbio" },
  AMBIGUOUS: { id: "ambiguous", color: "#ff6b35", emoji: "🔶", label: "ambigua" },
  ARTICLE: { id: "article", color: "#f39c12", emoji: "🟡", label: "artículo" },
  CONJUNCTION: { id: "conjunction", color: "#8b4513", emoji: "🟤", label: "conjunción" },
  FOREIGN: { id: "foreign", color: "#ff6b6b", emoji: "🌍", label: "extranjero" },
  INTERJECTION: { id: "interjection", color: "#6c757d", emoji: "💬", label: "interjección" },
  NOUN: { id: "noun", color: "#3498db", emoji: "🔵", label: "sustantivo" },
  NUMBER: { id: "number", color: "#17a2b8", emoji: "🔢", label: "número" },
  OTHER: { id: "other", color: "#95a5a6", emoji: "⚫", label: "otra" },
  PREPOSITION: { id: "preposition", color: "#9b59b6", emoji: "🟣", label: "preposición" },
  PRONOUN: { id: "pronoun", color: "#00d084", emoji: "🟢", label: "pronombre" },
  VERB: { id: "verb", color: "#e74c3c", emoji: "🔴", label: "verbo" },
};
