export const DET = { DEF: "def", INDEF: "indef", NONE: "none" };

export const DECLENSIONS = {
  [DET.DEF]: {
    "nom|m": "e",
    "nom|f": "e",
    "nom|n": "e",
    "nom|pl": "en",
    "akk|m": "en",
    "akk|f": "e",
    "akk|n": "e",
    "akk|pl": "en",
    "dat|m": "en",
    "dat|f": "en",
    "dat|n": "en",
    "dat|pl": "en",
    "gen|m": "en",
    "gen|f": "en",
    "gen|n": "en",
    "gen|pl": "en",
  },
  [DET.INDEF]: {
    "nom|m": "er",
    "nom|f": "e",
    "nom|n": "es",
    "nom|pl": "en",
    "akk|m": "en",
    "akk|f": "e",
    "akk|n": "es",
    "akk|pl": "en",
    "dat|m": "en",
    "dat|f": "en",
    "dat|n": "en",
    "dat|pl": "en",
    "gen|m": "en",
    "gen|f": "en",
    "gen|n": "en",
    "gen|pl": "en",
  },
  [DET.NONE]: {
    "nom|m": "er",
    "nom|f": "e",
    "nom|n": "es",
    "nom|pl": "e",
    "akk|m": "en",
    "akk|f": "e",
    "akk|n": "es",
    "akk|pl": "e",
    "dat|m": "em",
    "dat|f": "er",
    "dat|n": "em",
    "dat|pl": "en",
    "gen|m": "en",
    "gen|f": "er",
    "gen|n": "en",
    "gen|pl": "er",
  },
};
