export const ADJECTIVES_LANGUAGE = {
  englisch: {},
  deutsch: {},
  spanisch: {},
  französisch: {},
  italienisch: {},
  portugiesisch: {},
  niederländisch: {},
  schwedisch: {},
  dänisch: {},
  norwegisch: {},
  russisch: {},
  polnisch: {},
  tschechisch: {},
  griechisch: {},
  ungarisch: {},
  rumänisch: {},
  bulgarisch: {},
  slowenisch: {},
  kroatisch: {},
  serbisch: {},
  finnisch: {},
  estnisch: {},
  lettisch: {},
  litauisch: {},
};
