export const ADJECTIVES_LANGUAGE = [
  { de: "englisch", es: "inglés" },
  { de: "deutsch", es: "alemán" },
  { de: "spanisch", es: "español" },
  { de: "französisch", es: "francés" },
  { de: "italienisch", es: "italiano" },
  { de: "portugiesisch", es: "portugués" },
  { de: "niederländisch", es: "neerlandés / holandés" },
  { de: "schwedisch", es: "sueco" },
  { de: "dänisch", es: "danés" },
  { de: "norwegisch", es: "noruego" },
  { de: "russisch", es: "ruso" },
  { de: "polnisch", es: "polaco" },
  { de: "tschechisch", es: "checo" },
  { de: "griechisch", es: "griego" },
  { de: "ungarisch", es: "húngaro" },
  { de: "rumänisch", es: "rumano" },
  { de: "bulgarisch", es: "búlgaro" },
  { de: "slowenisch", es: "esloveno" },
  { de: "kroatisch", es: "croata" },
  { de: "serbisch", es: "serbio" },
  { de: "finnisch", es: "finés / finlandés" },
  { de: "estnisch", es: "estonio" },
  { de: "lettisch", es: "letón" },
  { de: "litauisch", es: "lituano" },
];
